In [2]:
import pandas as pd
df=pd.read_csv("car.csv")
print(df.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0                         ritz  2014           3.35          5.590       27000    Petrol      Dealer       Manual      0
1                          sx4  2013           4.75          9.540       43000    Diesel      Dealer       Manual      0
2                         ciaz  2017           7.25          9.850        6900    Petrol      Dealer       Manual      0
3                      wagon r  2011           2.85          4.150        5200    Petrol      Dealer       Manual      0
4                        swift  2014           4.60          6.870       42450    Diesel      Dealer       Manual      0
5                vitara brezza  2018           9.25          9.830        2071    Diesel      Dealer       Manual      0
6                         ciaz  2015           6.75          8.120       18796    Petrol      Dealer       Manual      0
7                      s cross  2015           6.50          8.610       33429    Diesel      Dealer       Manual      0
8                         ciaz  2016           8.75          8.890       20273    Diesel      Dealer       Manual      0
9                         ciaz  2015           7.45          8.920       42367    Diesel      Dealer       Manual      0
10                    alto 800  2017           2.85          3.600        2135    Petrol      Dealer       Manual      0
11                        ciaz  2015           6.85         10.380       51000    Diesel      Dealer       Manual      0
12                        ciaz  2015           7.50          9.940       15000    Petrol      Dealer    Automatic      0
13                      ertiga  2015           6.10          7.710       26000    Petrol      Dealer       Manual      0
14                       dzire  2009           2.25          7.210       77427    Petrol      Dealer       Manual      0
15                      ertiga  2016           7.75         10.790       43000    Diesel      Dealer       Manual      0
16                      ertiga  2015           7.25         10.790       41678    Diesel      Dealer       Manual      0
17                      ertiga  2016           7.75         10.790       43000    Diesel      Dealer       Manual      0
18                     wagon r  2015           3.25          5.090       35500       CNG      Dealer       Manual      0
19                         sx4  2010           2.65          7.980       41442    Petrol      Dealer       Manual      0
20                    alto k10  2016           2.85          3.950       25000    Petrol      Dealer       Manual      0
21                       ignis  2017           4.90          5.710        2400    Petrol      Dealer       Manual      0
22                         sx4  2011           4.40          8.010       50000    Petrol      Dealer    Automatic      0
23                    alto k10  2014           2.50          3.460       45280    Petrol      Dealer       Manual      0
24                     wagon r  2013           2.90          4.410       56879    Petrol      Dealer       Manual      0
25                       swift  2011           3.00          4.990       20000    Petrol      Dealer       Manual      0
26                       swift  2013           4.15          5.870       55138    Petrol      Dealer       Manual      0
27                       swift  2017           6.00          6.490       16200    Petrol  Individual       Manual      0
28                    alto k10  2010           1.95          3.950       44542    Petrol      Dealer       Manual      0
29                        ciaz  2015           7.45         10.380       45000    Diesel      Dealer       Manual      0
30                        ritz  2012           3.10          5.980       51439    Diesel      Dealer       Manual      0
31                        ritz  2011           2.35          4.890       54200    Petrol      Dealer       Manual      0
32                       swift  2014           4.95          7.490       39000    Diesel      Dealer       Manual      0
33                      ertiga  2014           6.00          9.950       45000    Diesel      Dealer       Manual      0
34                       dzire  2014           5.50          8.060       45000    Diesel      Dealer       Manual      0
35                         sx4  2011           2.95          7.740       49998       CNG      Dealer       Manual      0
36                       dzire  2015           4.65          7.200       48767    Petrol      Dealer       Manual      0
37                         800  2003           0.35          2.280      127000    Petrol  Individual       Manual      0
38                    alto k10  2016           3.00          3.760       10079    Petrol      Dealer       Manual      0
39                         sx4  2003           2.25          7.980       62000    Petrol      Dealer       Manual      0
40                      baleno  2016           5.85          7.870       24524    Petrol      Dealer    Automatic      0
41                    alto k10  2014           2.55          3.980       46706    Petrol      Dealer       Manual      0
42                         sx4  2008           1.95          7.150       58000    Petrol      Dealer       Manual      0
43                       dzire  2014           5.50          8.060       45780    Diesel      Dealer       Manual      0
44                        omni  2012           1.25          2.690       50000    Petrol      Dealer       Manual      0
45                        ciaz  2014           7.50         12.040       15000    Petrol      Dealer    Automatic      0
46                        ritz  2013           2.65          4.890       64532    Petrol      Dealer       Manual      0
47                     wagon r  2006           1.05          4.150       65000    Petrol      Dealer       Manual      0
48                      ertiga  2015           5.80          7.710       25870    Petrol      Dealer       Manual      0
49                        ciaz  2017           7.75          9.290       37000    Petrol      Dealer    Automatic      0
50                    fortuner  2012          14.90         30.610      104707    Diesel      Dealer    Automatic      0
51                    fortuner  2015          23.00         30.610       40000    Diesel      Dealer    Automatic      0
52                      innova  2017          18.00         19.770       15000    Diesel      Dealer    Automatic      0
53                    fortuner  2013          16.00         30.610      135000    Diesel  Individual    Automatic      0
54                      innova  2005           2.75         10.210       90000    Petrol  Individual       Manual      0
55               corolla altis  2009           3.60         15.040       70000    Petrol      Dealer    Automatic      0
56                 etios cross  2015           4.50          7.270       40534    Petrol      Dealer       Manual      0
57               corolla altis  2010           4.75         18.540       50000    Petrol      Dealer       Manual      0
58                     etios g  2014           4.10          6.800       39485    Petrol      Dealer       Manual      1
59                    fortuner  2014          19.99         35.960       41000    Diesel      Dealer    Automatic      0
60               corolla altis  2013           6.95         18.610       40001    Petrol      Dealer       Manual      0
61                 etios cross  2015           4.50          7.700       40588    Petrol      Dealer       Manual      0
62                    fortuner  2014          18.75         35.960       78000    Diesel      Dealer    Automatic      0
63                    fortuner  2015          23.50         35.960       47000    Diesel      Dealer    Automatic      0
64                    fortuner  2017          33.00         36.230        6000    Diesel      Dealer    Automatic      0
65                  etios liva  2014           4.75          6.950       45000    Diesel      Dealer       Manual      0
66                      innova  2017          19.75         23.150       11000    Petrol      Dealer    Automatic      0
67                    fortuner  2010           9.25         20.450       59000    Diesel      Dealer       Manual      0
68               corolla altis  2011           4.35         13.740       88000    Petrol      Dealer       Manual      0
69               corolla altis  2016          14.25         20.910       12000    Petrol      Dealer       Manual      0
70                  etios liva  2014           3.95          6.760       71000    Diesel      Dealer       Manual      0
71               corolla altis  2011           4.50         12.480       45000    Diesel      Dealer       Manual      0
72               corolla altis  2013           7.45         18.610       56001    Petrol      Dealer       Manual      0
73                  etios liva  2011           2.65          5.710       43000    Petrol      Dealer       Manual      0
74                 etios cross  2014           4.90          8.930       83000    Diesel      Dealer       Manual      0
75                     etios g  2015           3.95          6.800       36000    Petrol      Dealer       Manual      0
76               corolla altis  2013           5.50         14.680       72000    Petrol      Dealer       Manual      0
77                     corolla  2004           1.50         12.350      135154    Petrol      Dealer    Automatic      0
78               corolla altis  2010           5.25         22.830       80000    Petrol      Dealer    Automatic      0
79                    fortuner  2012          14.50         30.610       89000    Diesel      Dealer    Automatic      0
80               corolla altis  2016          14.73         14.890       23000    Diesel      Dealer       Manual      0
81                    etios gd  2015           4.75          7.850       40000    Diesel      Dealer       Manual      0
82                      innova  2017          23.00         25.390       15000    Diesel      Dealer    Automatic      0
83                      innova  2015          12.50         13.460       38000    Diesel      Dealer       Manual      0
84                      innova  2005           3.49         13.460      197176    Diesel      Dealer       Manual      0
85                       camry  2006           2.50         23.730      142000    Petrol  Individual    Automatic      3
86                land cruiser  2010          35.00         92.600       78000    Diesel      Dealer       Manual      0
87               corolla altis  2012           5.90         13.740       56000    Petrol      Dealer       Manual      0
88                  etios liva  2013           3.45          6.050       47000    Petrol      Dealer       Manual      0
89                     etios g  2014           4.75          6.760       40000    Petrol      Dealer       Manual      0
90               corolla altis  2009           3.80         18.610       62000    Petrol      Dealer       Manual      0
91                      innova  2014          11.25         16.090       58242    Diesel      Dealer       Manual      0
92                      innova  2005           3.51         13.700       75000    Petrol      Dealer       Manual      0
93                    fortuner  2015          23.00         30.610       40000    Diesel      Dealer    Automatic      0
94               corolla altis  2008           4.00         22.780       89000    Petrol      Dealer    Automatic      0
95               corolla altis  2012           5.85         18.610       72000    Petrol      Dealer       Manual      0
96                      innova  2016          20.75         25.390       29000    Diesel      Dealer    Automatic      0
97               corolla altis  2017          17.00         18.640        8700    Petrol      Dealer       Manual      0
98               corolla altis  2013           7.05         18.610       45000    Petrol      Dealer       Manual      0
99                    fortuner  2010           9.65         20.450       50024    Diesel      Dealer       Manual      0
100  Royal Enfield Thunder 500  2016           1.75          1.900        3000    Petrol  Individual       Manual      0
101         UM Renegade Mojave  2017           1.70          1.820        1400    Petrol  Individual       Manual      0
102                  KTM RC200  2017           1.65          1.780        4000    Petrol  Individual       Manual      0
103          Bajaj Dominar 400  2017           1.45          1.600        1200    Petrol  Individual       Manual      0
104  Royal Enfield Classic 350  2017           1.35          1.470        4100    Petrol  Individual       Manual      0
105                  KTM RC390  2015           1.35          2.370       21700    Petrol  Individual       Manual      0
106             Hyosung GT250R  2014           1.35          3.450       16500    Petrol  Individual       Manual      1
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0
108  Royal Enfield Thunder 350  2016           1.20          1.500       18000    Petrol  Individual       Manual      0
109  Royal Enfield Classic 350  2017           1.20          1.470       11000    Petrol  Individual       Manual      0
110                  KTM RC200  2016           1.20          1.780        6000    Petrol  Individual       Manual      0
111  Royal Enfield Thunder 350  2016           1.15          1.500        8700    Petrol  Individual       Manual      0
112              KTM 390 Duke   2014           1.15          2.400        7000    Petrol  Individual       Manual      0
113        Mahindra Mojo XT300  2016           1.15          1.400       35000    Petrol  Individual       Manual      0
114  Royal Enfield Classic 350  2015           1.15          1.470       17000    Petrol  Individual       Manual      0
115  Royal Enfield Classic 350  2015           1.11          1.470       17500    Petrol  Individual       Manual      0
116  Royal Enfield Classic 350  2013           1.10          1.470       33000    Petrol  Individual       Manual      0
117  Royal Enfield Thunder 500  2015           1.10          1.900       14000    Petrol  Individual       Manual      0
118  Royal Enfield Classic 350  2015           1.10          1.470       26000    Petrol  Individual       Manual      0
119  Royal Enfield Thunder 500  2013           1.05          1.900        5400    Petrol  Individual       Manual      0
120         Bajaj Pulsar RS200  2016           1.05          1.260        5700    Petrol  Individual       Manual      0
121  Royal Enfield Thunder 350  2011           1.05          1.500        6900    Petrol  Individual       Manual      0
122   Royal Enfield Bullet 350  2016           1.05          1.170        6000    Petrol  Individual       Manual      0
123  Royal Enfield Classic 350  2013           1.00          1.470       46500    Petrol  Individual       Manual      0
124  Royal Enfield Classic 500  2012           0.95          1.750       11500    Petrol  Individual       Manual      0
125  Royal Enfield Classic 500  2009           0.90          1.750       40000    Petrol  Individual       Manual      0
126          Bajaj Avenger 220  2017           0.90          0.950        1300    Petrol  Individual       Manual      0
127          Bajaj Avenger 150  2016           0.75          0.800        7000    Petrol  Individual       Manual      0
128       Honda CB Hornet 160R  2017           0.80          0.870        3000    Petrol  Individual       Manual      0
129          Yamaha FZ S V 2.0  2017           0.78          0.840        5000    Petrol  Individual       Manual      0
130       Honda CB Hornet 160R  2017           0.75          0.870       11000    Petrol  Individual       Manual      0
131               Yamaha FZ 16  2015           0.75          0.820       18000    Petrol  Individual       Manual      0
132          Bajaj Avenger 220  2017           0.75          0.950        3500    Petrol  Individual       Manual      0
133          Bajaj Avenger 220  2016           0.72          0.950         500    Petrol  Individual       Manual      0
134         TVS Apache RTR 160  2017           0.65          0.810       11800    Petrol  Individual       Manual      0
135           Bajaj Pulsar 150  2015           0.65          0.740        5000    Petrol  Individual       Manual      0
136              Honda CBR 150  2014           0.65          1.200       23500    Petrol  Individual       Manual      0
137               Hero Extreme  2013           0.65          0.787       16000    Petrol  Individual       Manual      0
138       Honda CB Hornet 160R  2016           0.60          0.870       15000    Petrol  Individual       Manual      0
139     Bajaj Avenger 220 dtsi  2015           0.60          0.950       16600    Petrol  Individual       Manual      0
140              Honda CBR 150  2013           0.60          1.200       32000    Petrol  Individual       Manual      0
141   Bajaj Avenger 150 street  2016           0.60          0.800       20000    Petrol  Individual       Manual      0
142           Yamaha FZ  v 2.0  2015           0.60          0.840       29000    Petrol  Individual       Manual      0
143           Yamaha FZ  v 2.0  2016           0.60          0.840       25000    Petrol  Individual       Manual      0
144       Bajaj Pulsar  NS 200  2014           0.60          0.990       25000    Petrol  Individual       Manual      0
145         TVS Apache RTR 160  2012           0.60          0.810       19000    Petrol  Individual       Manual      0
146               Hero Extreme  2014           0.55          0.787       15000    Petrol  Individual       Manual      0
147          Yamaha FZ S V 2.0  2015           0.55          0.840       58000    Petrol  Individual       Manual      0
148         Bajaj Pulsar 220 F  2010           0.52          0.940       45000    Petrol  Individual       Manual      0
149         Bajaj Pulsar 220 F  2016           0.51          0.940       24000    Petrol  Individual       Manual      0
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0
151         Hero Passion X pro  2016           0.50          0.550       31000    Petrol  Individual       Manual      0
152        Bajaj Pulsar NS 200  2012           0.50          0.990       13000    Petrol  Individual       Manual      0
153        Bajaj Pulsar NS 200  2013           0.50          0.990       45000    Petrol  Individual       Manual      0
154              Yamaha Fazer   2014           0.50          0.880        8000    Petrol  Individual       Manual      0
155            Honda Activa 4G  2017           0.48          0.510        4300    Petrol  Individual    Automatic      0
156                 TVS Sport   2017           0.48          0.520       15000    Petrol  Individual       Manual      0
157          Yamaha FZ S V 2.0  2015           0.48          0.840       23000    Petrol  Individual       Manual      0
158          Honda Dream Yuga   2017           0.48          0.540        8600    Petrol  Individual       Manual      0
159            Honda Activa 4G  2017           0.45          0.510        4000    Petrol  Individual    Automatic      0
160   Bajaj Avenger Street 220  2011           0.45          0.950       24000    Petrol  Individual       Manual      0
161         TVS Apache RTR 180  2014           0.45          0.826       23000    Petrol  Individual       Manual      0
162        Bajaj Pulsar NS 200  2012           0.45          0.990       14500    Petrol  Individual       Manual      0
163     Bajaj Avenger 220 dtsi  2010           0.45          0.950       27000    Petrol  Individual       Manual      0

In [2]:
print(pd.options.display.max_rows)

60

In [3]:
pd.options.display.max_rows = 9999
print(df)

                      Car_Name  Year  Selling_Price  Present_Price  \
0                         ritz  2014           3.35          5.590
1                          sx4  2013           4.75          9.540
2                         ciaz  2017           7.25          9.850
3                      wagon r  2011           2.85          4.150
4                        swift  2014           4.60          6.870
5                vitara brezza  2018           9.25          9.830
6                         ciaz  2015           6.75          8.120
7                      s cross  2015           6.50          8.610
8                         ciaz  2016           8.75          8.890
9                         ciaz  2015           7.45          8.920
10                    alto 800  2017           2.85          3.600
11                        ciaz  2015           6.85         10.380
12                        ciaz  2015           7.50          9.940
13                      ertiga  2015           6.10          7.710
14                       dzire  2009           2.25          7.210
15                      ertiga  2016           7.75         10.790
16                      ertiga  2015           7.25         10.790
17                      ertiga  2016           7.75         10.790
18                     wagon r  2015           3.25          5.090
19                         sx4  2010           2.65          7.980
20                    alto k10  2016           2.85          3.950
21                       ignis  2017           4.90          5.710
22                         sx4  2011           4.40          8.010
23                    alto k10  2014           2.50          3.460
24                     wagon r  2013           2.90          4.410
25                       swift  2011           3.00          4.990
26                       swift  2013           4.15          5.870
27                       swift  2017           6.00          6.490
28                    alto k10  2010           1.95          3.950
29                        ciaz  2015           7.45         10.380
30                        ritz  2012           3.10          5.980
31                        ritz  2011           2.35          4.890
32                       swift  2014           4.95          7.490
33                      ertiga  2014           6.00          9.950
34                       dzire  2014           5.50          8.060
35                         sx4  2011           2.95          7.740
36                       dzire  2015           4.65          7.200
37                         800  2003           0.35          2.280
38                    alto k10  2016           3.00          3.760
39                         sx4  2003           2.25          7.980
40                      baleno  2016           5.85          7.870
41                    alto k10  2014           2.55          3.980
42                         sx4  2008           1.95          7.150
43                       dzire  2014           5.50          8.060
44                        omni  2012           1.25          2.690
45                        ciaz  2014           7.50         12.040
46                        ritz  2013           2.65          4.890
47                     wagon r  2006           1.05          4.150
48                      ertiga  2015           5.80          7.710
49                        ciaz  2017           7.75          9.290
50                    fortuner  2012          14.90         30.610
51                    fortuner  2015          23.00         30.610
52                      innova  2017          18.00         19.770
53                    fortuner  2013          16.00         30.610
54                      innova  2005           2.75         10.210
55               corolla altis  2009           3.60         15.040
56                 etios cross  2015           4.50          7.270
57               corolla altis  2010           4.75         18.540
58                     etios g  2014           4.10          6.800
59                    fortuner  2014          19.99         35.960
60               corolla altis  2013           6.95         18.610
61                 etios cross  2015           4.50          7.700
62                    fortuner  2014          18.75         35.960
63                    fortuner  2015          23.50         35.960
64                    fortuner  2017          33.00         36.230
65                  etios liva  2014           4.75          6.950
66                      innova  2017          19.75         23.150
67                    fortuner  2010           9.25         20.450
68               corolla altis  2011           4.35         13.740
69               corolla altis  2016          14.25         20.910
70                  etios liva  2014           3.95          6.760
71               corolla altis  2011           4.50         12.480
72               corolla altis  2013           7.45         18.610
73                  etios liva  2011           2.65          5.710
74                 etios cross  2014           4.90          8.930
75                     etios g  2015           3.95          6.800
76               corolla altis  2013           5.50         14.680
77                     corolla  2004           1.50         12.350
78               corolla altis  2010           5.25         22.830
79                    fortuner  2012          14.50         30.610
80               corolla altis  2016          14.73         14.890
81                    etios gd  2015           4.75          7.850
82                      innova  2017          23.00         25.390
83                      innova  2015          12.50         13.460
84                      innova  2005           3.49         13.460
85                       camry  2006           2.50         23.730
86                land cruiser  2010          35.00         92.600
87               corolla altis  2012           5.90         13.740
88                  etios liva  2013           3.45          6.050
89                     etios g  2014           4.75          6.760
90               corolla altis  2009           3.80         18.610
91                      innova  2014          11.25         16.090
92                      innova  2005           3.51         13.700
93                    fortuner  2015          23.00         30.610
94               corolla altis  2008           4.00         22.780
95               corolla altis  2012           5.85         18.610
96                      innova  2016          20.75         25.390
97               corolla altis  2017          17.00         18.640
98               corolla altis  2013           7.05         18.610
99                    fortuner  2010           9.65         20.450
100  Royal Enfield Thunder 500  2016           1.75          1.900
101         UM Renegade Mojave  2017           1.70          1.820
102                  KTM RC200  2017           1.65          1.780
103          Bajaj Dominar 400  2017           1.45          1.600
104  Royal Enfield Classic 350  2017           1.35          1.470
105                  KTM RC390  2015           1.35          2.370
106             Hyosung GT250R  2014           1.35          3.450
107  Royal Enfield Thunder 350  2013           1.25          1.500
108  Royal Enfield Thunder 350  2016           1.20          1.500
109  Royal Enfield Classic 350  2017           1.20          1.470
110                  KTM RC200  2016           1.20          1.780
111  Royal Enfield Thunder 350  2016           1.15          1.500
112              KTM 390 Duke   2014           1.15          2.400
113        Mahindra Mojo XT300  2016           1.15          1.400
114  Royal Enfield Classic 350  2015           1.15          1.470
115  Royal Enfield Classic 350  2015           1.11          1.470
116  Royal Enfield Classic 350  2013           1.10          1.470
117  Royal Enfield Thunder 500  2015           1.10          1.900
118  Royal Enfield Classic 350  2015           1.10          1.470
119  Royal Enfield Thunder 500  2013           1.05          1.900
120         Bajaj Pulsar RS200  2016           1.05          1.260
121  Royal Enfield Thunder 350  2011           1.05          1.500
122   Royal Enfield Bullet 350  2016           1.05          1.170
123  Royal Enfield Classic 350  2013           1.00          1.470
124  Royal Enfield Classic 500  2012           0.95          1.750
125  Royal Enfield Classic 500  2009           0.90          1.750
126          Bajaj Avenger 220  2017           0.90          0.950
127          Bajaj Avenger 150  2016           0.75          0.800
128       Honda CB Hornet 160R  2017           0.80          0.870
129          Yamaha FZ S V 2.0  2017           0.78          0.840
130       Honda CB Hornet 160R  2017           0.75          0.870
131               Yamaha FZ 16  2015           0.75          0.820
132          Bajaj Avenger 220  2017           0.75          0.950
133          Bajaj Avenger 220  2016           0.72          0.950
134         TVS Apache RTR 160  2017           0.65          0.810
135           Bajaj Pulsar 150  2015           0.65          0.740
136              Honda CBR 150  2014           0.65          1.200
137               Hero Extreme  2013           0.65          0.787
138       Honda CB Hornet 160R  2016           0.60          0.870
139     Bajaj Avenger 220 dtsi  2015           0.60          0.950
140              Honda CBR 150  2013           0.60          1.200
141   Bajaj Avenger 150 street  2016           0.60          0.800
142           Yamaha FZ  v 2.0  2015           0.60          0.840
143           Yamaha FZ  v 2.0  2016           0.60          0.840
144       Bajaj Pulsar  NS 200  2014           0.60          0.990
145         TVS Apache RTR 160  2012           0.60          0.810
146               Hero Extreme  2014           0.55          0.787
147          Yamaha FZ S V 2.0  2015           0.55          0.840
148         Bajaj Pulsar 220 F  2010           0.52          0.940
149         Bajaj Pulsar 220 F  2016           0.51          0.940
150         TVS Apache RTR 180  2011           0.50          0.826
151         Hero Passion X pro  2016           0.50          0.550
152        Bajaj Pulsar NS 200  2012           0.50          0.990
153        Bajaj Pulsar NS 200  2013           0.50          0.990
154              Yamaha Fazer   2014           0.50          0.880
155            Honda Activa 4G  2017           0.48          0.510
156                 TVS Sport   2017           0.48          0.520
157          Yamaha FZ S V 2.0  2015           0.48          0.840
158          Honda Dream Yuga   2017           0.48          0.540
159            Honda Activa 4G  2017           0.45          0.510
160   Bajaj Avenger Street 220  2011           0.45          0.950
161         TVS Apache RTR 180  2014           0.45          0.826
162        Bajaj Pulsar NS 200  2012           0.45          0.990
163     Bajaj Avenger 220 dtsi  2010           0.45          0.950
164       Hero Splender iSmart  2016           0.45          0.540
165                  Activa 3g  2016           0.45          0.540
166           Hero Passion Pro  2016           0.45          0.550
167         TVS Apache RTR 160  2014           0.42          0.810
168           Honda CB Trigger  2013           0.42          0.730
169       Hero Splender iSmart  2015           0.40          0.540
170               Yamaha FZ S   2012           0.40          0.830
171           Hero Passion Pro  2015           0.40          0.550
172        Bajaj Pulsar 135 LS  2014           0.40          0.640
173                  Activa 4g  2017           0.40          0.510
174           Honda CB Unicorn  2015           0.38          0.720
175     Hero Honda CBZ extreme  2011           0.38          0.787
176              Honda Karizma  2011           0.35          1.050
177           Honda Activa 125  2016           0.35          0.570
178                TVS Jupyter  2014           0.35          0.520
179              Honda Karizma  2010           0.31          1.050
180     Hero Honda Passion Pro  2012           0.30          0.510
181         Hero Splender Plus  2016           0.30          0.480
182             Honda CB Shine  2013           0.30          0.580
183         Bajaj Discover 100  2013           0.27          0.470
184           Bajaj Pulsar 150  2008           0.25          0.750
185          Suzuki Access 125  2008           0.25          0.580
186                   TVS Wego  2010           0.25          0.520
187           Honda CB twister  2013           0.25          0.510
188               Hero Glamour  2013           0.25          0.570
189        Hero Super Splendor  2005           0.20          0.570
190           Bajaj Pulsar 150  2008           0.20          0.750
191         Bajaj Discover 125  2012           0.20          0.570
192                  Hero Hunk  2007           0.20          0.750
193         Hero  Ignitor Disc  2013           0.20          0.650
194           Hero  CBZ Xtreme  2008           0.20          0.787
195              Bajaj  ct 100  2015           0.18          0.320
196                  Activa 3g  2008           0.17          0.520
197           Honda CB twister  2010           0.16          0.510
198         Bajaj Discover 125  2011           0.15          0.570
199             Honda CB Shine  2007           0.12          0.580
200           Bajaj Pulsar 150  2006           0.10          0.750
201                        i20  2010           3.25          6.790
202                  grand i10  2015           4.40          5.700
203                        i10  2011           2.95          4.600
204                        eon  2015           2.75          4.430
205                  grand i10  2016           5.25          5.700
206                      xcent  2017           5.75          7.130
207                  grand i10  2015           5.15          5.700
208                        i20  2017           7.90          8.100
209                  grand i10  2015           4.85          5.700
210                        i10  2012           3.10          4.600
211                    elantra  2015          11.75         14.790
212                      creta  2016          11.25         13.600
213                        i20  2011           2.90          6.790
214                  grand i10  2017           5.25          5.700
215                      verna  2012           4.50          9.400
216                        eon  2016           2.90          4.430
217                        eon  2016           3.15          4.430
218                      verna  2014           6.45          9.400
219                      verna  2012           4.50          9.400
220                        eon  2017           3.50          4.430
221                        i20  2013           4.50          6.790
222                        i20  2014           6.00          7.600
223                      verna  2015           8.25          9.400
224                      verna  2013           5.11          9.400
225                        i10  2011           2.70          4.600
226                  grand i10  2015           5.25          5.700
227                        i10  2011           2.55          4.430
228                      verna  2012           4.95          9.400
229                        i20  2012           3.10          6.790
230                      verna  2013           6.15          9.400
231                      verna  2017           9.25          9.400
232                    elantra  2015          11.45         14.790
233                  grand i10  2013           3.90          5.700
234                  grand i10  2015           5.50          5.700
235                      verna  2017           9.10          9.400
236                        eon  2016           3.10          4.430
237                      creta  2015          11.25         13.600
238                      verna  2013           4.80          9.400
239                        eon  2012           2.00          4.430
240                      verna  2012           5.35          9.400
241                      xcent  2015           4.75          7.130
242                      xcent  2014           4.40          7.130
243                        i20  2016           6.25          7.600
244                      verna  2013           5.95          9.400
245                      verna  2012           5.20          9.400
246                        i20  2012           3.75          6.790
247                      verna  2015           5.95          9.400
248                        i10  2013           4.00          4.600
249                        i20  2016           5.25          7.600
250                      creta  2016          12.90         13.600
251                       city  2013           5.00          9.900
252                       brio  2015           5.40          6.820
253                       city  2014           7.20          9.900
254                       city  2013           5.25          9.900
255                       brio  2012           3.00          5.350
256                       city  2016          10.25         13.600
257                       city  2015           8.50         13.600
258                       city  2015           8.40         13.600
259                      amaze  2014           3.90          7.000
260                       city  2016           9.15         13.600
261                       brio  2016           5.50          5.970
262                      amaze  2015           4.00          5.800
263                       jazz  2016           6.60          7.700
264                      amaze  2015           4.00          7.000
265                       jazz  2017           6.50          8.700
266                      amaze  2014           3.65          7.000
267                       city  2016           8.35          9.400
268                       brio  2017           4.80          5.800
269                       city  2015           6.70         10.000
270                       city  2011           4.10         10.000
271                       city  2009           3.00         10.000
272                       city  2015           7.50         10.000
273                       jazz  2010           2.25          7.500
274                       brio  2014           5.30          6.800
275                       city  2016          10.90         13.600
276                       city  2015           8.65         13.600
277                       city  2015           9.70         13.600
278                       jazz  2016           6.00          8.400
279                       city  2014           6.25         13.600
280                       brio  2015           5.25          5.900
281                       city  2006           2.10          7.600
282                       city  2014           8.25         14.000
283                       city  2016           8.99         11.800
284                       brio  2013           3.50          5.900
285                       jazz  2016           7.40          8.500
286                       jazz  2016           5.65          7.900
287                      amaze  2015           5.75          7.500
288                       city  2015           8.40         13.600
289                       city  2016          10.11         13.600
290                      amaze  2014           4.50          6.400
291                       brio  2015           5.40          6.100
292                       jazz  2016           6.40          8.400
293                       city  2010           3.25          9.900
294                      amaze  2014           3.75          6.800
295                       city  2015           8.55         13.090
296                       city  2016           9.50         11.600

In [4]:
dates = ['dd\mm\yyyy']
df1=df.sample(n=10,random_state=1)
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500
248                        i10  2013           4.00          4.600
150         TVS Apache RTR 180  2011           0.50          0.826
217                        eon  2016           3.15          4.430
107  Royal Enfield Thunder 350  2013           1.25          1.500
206                      xcent  2017           5.75          7.130
132          Bajaj Avenger 220  2017           0.75          0.950
73                  etios liva  2011           2.65          5.710
288                       city  2015           8.40         13.600
157          Yamaha FZ S V 2.0  2015           0.48          0.840

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner
285       15059    Petrol      Dealer    Automatic      0
248       30000    Petrol      Dealer       Manual      0
150        6000    Petrol  Individual       Manual      0
217       15000    Petrol      Dealer       Manual      0
107       15000    Petrol  Individual       Manual      0
206       12479    Petrol      Dealer       Manual      0
132        3500    Petrol  Individual       Manual      0
73        43000    Petrol      Dealer       Manual      0
288       34000    Petrol      Dealer       Manual      0
157       23000    Petrol  Individual       Manual      0

In [5]:
dates = ['10-01-2004','11-01-2004','12-01-2004','13-01-2004','14-01-2004','15-01-2004','16-01-2004','17-01-2004','18-01-2004','19-01-2004']
df1=df.sample(n=10,random_state=1)
#df1['datesPurchased']=dates
print(df1)

                      Car_Name  Year  Selling_Price  Present_Price  \
285                       jazz  2016           7.40          8.500
248                        i10  2013           4.00          4.600
150         TVS Apache RTR 180  2011           0.50          0.826
217                        eon  2016           3.15          4.430
107  Royal Enfield Thunder 350  2013           1.25          1.500
206                      xcent  2017           5.75          7.130
132          Bajaj Avenger 220  2017           0.75          0.950
73                  etios liva  2011           2.65          5.710
288                       city  2015           8.40         13.600
157          Yamaha FZ S V 2.0  2015           0.48          0.840

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner
285       15059    Petrol      Dealer    Automatic      0
248       30000    Petrol      Dealer       Manual      0
150        6000    Petrol  Individual       Manual      0
217       15000    Petrol      Dealer       Manual      0
107       15000    Petrol  Individual       Manual      0
206       12479    Petrol      Dealer       Manual      0
132        3500    Petrol  Individual       Manual      0
73        43000    Petrol      Dealer       Manual      0
288       34000    Petrol      Dealer       Manual      0
157       23000    Petrol  Individual       Manual      0

In [6]:
df1['datePurchased']=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0    15-01-2004
132          Bajaj Avenger 220  2017           0.75          0.950        3500    Petrol  Individual       Manual      0    16-01-2004
73                  etios liva  2011           2.65          5.710       43000    Petrol      Dealer       Manual      0    17-01-2004
288                       city  2015           8.40         13.600       34000    Petrol      Dealer       Manual      0    18-01-2004
157          Yamaha FZ S V 2.0  2015           0.48          0.840       23000    Petrol  Individual       Manual      0    19-01-2004

In [9]:
df1["datesPurchased"]=dates
print(df1.to_string())

                      Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner datePurchased datesPurchased
285                       jazz  2016           7.40          8.500       15059    Petrol      Dealer    Automatic      0    10-01-2004     10-01-2004
248                        i10  2013           4.00          4.600       30000    Petrol      Dealer       Manual      0    11-01-2004     11-01-2004
150         TVS Apache RTR 180  2011           0.50          0.826        6000    Petrol  Individual       Manual      0    12-01-2004     12-01-2004
217                        eon  2016           3.15          4.430       15000    Petrol      Dealer       Manual      0    13-01-2004     13-01-2004
107  Royal Enfield Thunder 350  2013           1.25          1.500       15000    Petrol  Individual       Manual      0    14-01-2004     14-01-2004
206                      xcent  2017           5.75          7.130       12479    Petrol      Dealer       Manual      0    15-01-2004     15-01-2004
132          Bajaj Avenger 220  2017           0.75          0.950        3500    Petrol  Individual       Manual      0    16-01-2004     16-01-2004
73                  etios liva  2011           2.65          5.710       43000    Petrol      Dealer       Manual      0    17-01-2004     17-01-2004
288                       city  2015           8.40         13.600       34000    Petrol      Dealer       Manual      0    18-01-2004     18-01-2004
157          Yamaha FZ S V 2.0  2015           0.48          0.840       23000    Petrol  Individual       Manual      0    19-01-2004     19-01-2004

In [10]:
df.to_excel("output.xlsx")
pd.read_excel("output.xlsx")

,Unnamed: 0,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,0,ritz,2014,3.35,5.590,27000,Petrol,Dealer,Manual,0
1,1,sx4,2013,4.75,9.540,43000,Diesel,Dealer,Manual,0
2,2,ciaz,2017,7.25,9.850,6900,Petrol,Dealer,Manual,0
3,3,wagon r,2011,2.85,4.150,5200,Petrol,Dealer,Manual,0
4,4,swift,2014,4.60,6.870,42450,Diesel,Dealer,Manual,0
5,5,vitara brezza,2018,9.25,9.830,2071,Diesel,Dealer,Manual,0
6,6,ciaz,2015,6.75,8.120,18796,Petrol,Dealer,Manual,0
7,7,s cross,2015,6.50,8.610,33429,Diesel,Dealer,Manual,0
8,8,ciaz,2016,8.75,8.890,20273,Diesel,Dealer,Manual,0
9,9,ciaz,2015,7.45,8.920,42367,Diesel,Dealer,Manual,0
10,10,alto 800,2017,2.85,3.600,2135,Petrol,Dealer,Manual,0
11,11,ciaz,2015,6.85,10.380,51000,Diesel,Dealer,Manual,0
12,12,ciaz,2015,7.50,9.940,15000,Petrol,Dealer,Automatic,0
13,13,ertiga,2015,6.10,7.710,26000,Petrol,Dealer,Manual,0
14,14,dzire,2009,2.25,7.210,77427,Petrol,Dealer,Manual,0
15,15,ertiga,2016,7.75,10.790,43000,Diesel,Dealer,Manual,0
16,16,ertiga,2015,7.25,10.790,41678,Diesel,Dealer,Manual,0
17,17,ertiga,2016,7.75,10.790,43000,Diesel,Dealer,Manual,0
18,18,wagon r,2015,3.25,5.090,35500,CNG,Dealer,Manual,0
19,19,sx4,2010,2.65,7.980,41442,Petrol,Dealer,Manual,0
20,20,alto k10,2016,2.85,3.950,25000,Petrol,Dealer,Manual,0
21,21,ignis,2017,4.90,5.710,2400,Petrol,Dealer,Manual,0
22,22,sx4,2011,4.40,8.010,50000,Petrol,Dealer,Automatic,0
23,23,alto k10,2014,2.50,3.460,45280,Petrol,Dealer,Manual,0
24,24,wagon r,2013,2.90,4.410,56879,Petrol,Dealer,Manual,0
25,25,swift,2011,3.00,4.990,20000,Petrol,Dealer,Manual,0
26,26,swift,2013,4.15,5.870,55138,Petrol,Dealer,Manual,0
27,27,swift,2017,6.00,6.490,16200,Petrol,Individual,Manual,0
28,28,alto k10,2010,1.95,3.950,44542,Petrol,Dealer,Manual,0
29,29,ciaz,2015,7.45,10.380,45000,Diesel,Dealer,Manual,0
30,30,ritz,2012,3.10,5.980,51439,Diesel,Dealer,Manual,0
31,31,ritz,2011,2.35,4.890,54200,Petrol,Dealer,Manual,0
32,32,swift,2014,4.95,7.490,39000,Diesel,Dealer,Manual,0
33,33,ertiga,2014,6.00,9.950,45000,Diesel,Dealer,Manual,0
34,34,dzire,2014,5.50,8.060,45000,Diesel,Dealer,Manual,0
35,35,sx4,2011,2.95,7.740,49998,CNG,Dealer,Manual,0
36,36,dzire,2015,4.65,7.200,48767,Petrol,Dealer,Manual,0
37,37,800,2003,0.35,2.280,127000,Petrol,Individual,Manual,0
38,38,alto k10,2016,3.00,3.760,10079,Petrol,Dealer,Manual,0
39,39,sx4,2003,2.25,7.980,62000,Petrol,Dealer,Manual,0
40,40,baleno,2016,5.85,7.870,24524,Petrol,Dealer,Automatic,0
41,41,alto k10,2014,2.55,3.980,46706,Petrol,Dealer,Manual,0
42,42,sx4,2008,1.95,7.150,58000,Petrol,Dealer,Manual,0
43,43,dzire,2014,5.50,8.060,45780,Diesel,Dealer,Manual,0
44,44,omni,2012,1.25,2.690,50000,Petrol,Dealer,Manual,0
45,45,ciaz,2014,7.50,12.040,15000,Petrol,Dealer,Automatic,0
46,46,ritz,2013,2.65,4.890,64532,Petrol,Dealer,Manual,0
47,47,wagon r,2006,1.05,4.150,65000,Petrol,Dealer,Manual,0
48,48,ertiga,2015,5.80,7.710,25870,Petrol,Dealer,Manual,0
49,49,ciaz,2017,7.75,9.290,37000,Petrol,Dealer,Automatic,0
50,50,fortuner,2012,14.90,30.610,104707,Diesel,Dealer,Automatic,0
51,51,fortuner,2015,23.00,30.610,40000,Diesel,Dealer,Automatic,0
52,52,innova,2017,18.00,19.770,15000,Diesel,Dealer,Automatic,0
53,53,fortuner,2013,16.00,30.610,135000,Diesel,Individual,Automatic,0
54,54,innova,2005,2.75,10.210,90000,Petrol,Individual,Manual,0
55,55,corolla altis,2009,3.60,15.040,70000,Petrol,Dealer,Automatic,0
56,56,etios cross,2015,4.50,7.270,40534,Petrol,Dealer,Manual,0
57,57,corolla altis,2010,4.75,18.540,50000,Petrol,Dealer,Manual,0
58,58,etios g,2014,4.10,6.800,39485,Petrol,Dealer,Manual,1
59,59,fortuner,2014,19.99,35.960,41000,Diesel,Dealer,Automatic,0
60,60,corolla altis,2013,6.95,18.610,40001,Petrol,Dealer,Manual,0
61,61,etios cross,2015,4.50,7.700,40588,Petrol,Dealer,Manual,0
62,62,fortuner,2014,18.75,35.960,78000,Diesel,Dealer,Automatic,0
63,63,fortuner,2015,23.50,35.960,47000,Diesel,Dealer,Automatic,0
64,64,fortuner,2017,33.00,36.230,6000,Diesel,Dealer,Automatic,0
65,65,etios liva,2014,4.75,6.950,45000,Diesel,Dealer,Manual,0
66,66,innova,2017,19.75,23.150,11000,Petrol,Dealer,Automatic,0
67,67,fortuner,2010,9.25,20.450,59000,Diesel,Dealer,Manual,0
68,68,corolla altis,2011,4.35,13.740,88000,Petrol,Dealer,Manual,0
69,69,corolla altis,2016,14.25,20.910,12000,Petrol,Dealer,Manual,0
70,70,etios liva,2014,3.95,6.760,71000,Diesel,Dealer,Manual,0
71,71,corolla altis,2011,4.50,12.480,45000,Diesel,Dealer,Manual,0
72,72,corolla altis,2013,7.45,18.610,56001,Petrol,Dealer,Manual,0
73,73,etios liva,2011,2.65,5.710,43000,Petrol,Dealer,Manual,0
74,74,etios cross,2014,4.90,8.930,83000,Diesel,Dealer,Manual,0
75,75,etios g,2015,3.95,6.800,36000,Petrol,Dealer,Manual,0
76,76,corolla altis,2013,5.50,14.680,72000,Petrol,Dealer,Manual,0
77,77,corolla,2004,1.50,12.350,135154,Petrol,Dealer,Automatic,0
78,78,corolla altis,2010,5.25,22.830,80000,Petrol,Dealer,Automatic,0
79,79,fortuner,2012,14.50,30.610,89000,Diesel,Dealer,Automatic,0
80,80,corolla altis,2016,14.73,14.890,23000,Diesel,Dealer,Manual,0
81,81,etios gd,2015,4.75,7.850,40000,Diesel,Dealer,Manual,0
82,82,innova,2017,23.00,25.390,15000,Diesel,Dealer,Automatic,0
83,83,innova,2015,12.50,13.460,38000,Diesel,Dealer,Manual,0
84,84,innova,2005,3.49,13.460,197176,Diesel,Dealer,Manual,0
85,85,camry,2006,2.50,23.730,142000,Petrol,Individual,Automatic,3
86,86,land cruiser,2010,35.00,92.600,78000,Diesel,Dealer,Manual,0
87,87,corolla altis,2012,5.90,13.740,56000,Petrol,Dealer,Manual,0
88,88,etios liva,2013,3.45,6.050,47000,Petrol,Dealer,Manual,0
89,89,etios g,2014,4.75,6.760,40000,Petrol,Dealer,Manual,0
90,90,corolla altis,2009,3.80,18.610,62000,Petrol,Dealer,Manual,0
91,91,innova,2014,11.25,16.090,58242,Diesel,Dealer,Manual,0
92,92,innova,2005,3.51,13.700,75000,Petrol,Dealer,Manual,0
93,93,fortuner,2015,23.00,30.610,40000,Diesel,Dealer,Automatic,0
94,94,corolla altis,2008,4.00,22.780,89000,Petrol,Dealer,Automatic,0
95,95,corolla altis,2012,5.85,18.610,72000,Petrol,Dealer,Manual,0
96,96,innova,2016,20.75,25.390,29000,Diesel,Dealer,Automatic,0
97,97,corolla altis,2017,17.00,18.640,8700,Petrol,Dealer,Manual,0
98,98,corolla altis,2013,7.05,18.610,45000,Petrol,Dealer,Manual,0
99,99,fortuner,2010,9.65,20.450,50024,Diesel,Dealer,Manual,0
100,100,Royal Enfield Thunder 500,2016,1.75,1.900,3000,Petrol,Individual,Manual,0
101,101,UM Renegade Mojave,2017,1.70,1.820,1400,Petrol,Individual,Manual,0
102,102,KTM RC200,2017,1.65,1.780,4000,Petrol,Individual,Manual,0
103,103,Bajaj Dominar 400,2017,1.45,1.600,1200,Petrol,Individual,Manual,0
104,104,Royal Enfield Classic 350,2017,1.35,1.470,4100,Petrol,Individual,Manual,0
105,105,KTM RC390,2015,1.35,2.370,21700,Petrol,Individual,Manual,0
106,106,Hyosung GT250R,2014,1.35,3.450,16500,Petrol,Individual,Manual,1
107,107,Royal Enfield Thunder 350,2013,1.25,1.500,15000,Petrol,Individual,Manual,0
108,108,Royal Enfield Thunder 350,2016,1.20,1.500,18000,Petrol,Individual,Manual,0
109,109,Royal Enfield Classic 350,2017,1.20,1.470,11000,Petrol,Individual,Manual,0
110,110,KTM RC200,2016,1.20,1.780,6000,Petrol,Individual,Manual,0
111,111,Royal Enfield Thunder 350,2016,1.15,1.500,8700,Petrol,Individual,Manual,0
112,112,KTM 390 Duke,2014,1.15,2.400,7000,Petrol,Individual,Manual,0
113,113,Mahindra Mojo XT300,2016,1.15,1.400,35000,Petrol,Individual,Manual,0
114,114,Royal Enfield Classic 350,2015,1.15,1.470,17000,Petrol,Individual,Manual,0
115,115,Royal Enfield Classic 350,2015,1.11,1.470,17500,Petrol,Individual,Manual,0
116,116,Royal Enfield Classic 350,2013,1.10,1.470,33000,Petrol,Individual,Manual,0
117,117,Royal Enfield Thunder 500,2015,1.10,1.900,14000,Petrol,Individual,Manual,0
118,118,Royal Enfield Classic 350,2015,1.10,1.470,26000,Petrol,Individual,Manual,0
119,119,Royal Enfield Thunder 500,2013,1.05,1.900,5400,Petrol,Individual,Manual,0
120,120,Bajaj Pulsar RS200,2016,1.05,1.260,5700,Petrol,Individual,Manual,0
121,121,Royal Enfield Thunder 350,2011,1.05,1.500,6900,Petrol,Individual,Manual,0
122,122,Royal Enfield Bullet 350,2016,1.05,1.170,6000,Petrol,Individual,Manual,0
123,123,Royal Enfield Classic 350,2013,1.00,1.470,46500,Petrol,Individual,Manual,0
124,124,Royal Enfield Classic 500,2012,0.95,1.750,11500,Petrol,Individual,Manual,0
125,125,Royal Enfield Classic 500,2009,0.90,1.750,40000,Petrol,Individual,Manual,0
126,126,Bajaj Avenger 220,2017,0.90,0.950,1300,Petrol,Individual,Manual,0
127,127,Bajaj Avenger 150,2016,0.75,0.800,7000,Petrol,Individual,Manual,0
128,128,Honda CB Hornet 160R,2017,0.80,0.870,3000,Petrol,Individual,Manual,0
129,129,Yamaha FZ S V 2.0,2017,0.78,0.840,5000,Petrol,Individual,Manual,0
130,130,Honda CB Hornet 160R,2017,0.75,0.870,11000,Petrol,Individual,Manual,0
131,131,Yamaha FZ 16,2015,0.75,0.820,18000,Petrol,Individual,Manual,0
132,132,Bajaj Avenger 220,2017,0.75,0.950,3500,Petrol,Individual,Manual,0
133,133,Bajaj Avenger 220,2016,0.72,0.950,500,Petrol,Individual,Manual,0
134,134,TVS Apache RTR 160,2017,0.65,0.810,11800,Petrol,Individual,Manual,0
135,135,Bajaj Pulsar 150,2015,0.65,0.740,5000,Petrol,Individual,Manual,0
136,136,Honda CBR 150,2014,0.65,1.200,23500,Petrol,Individual,Manual,0
137,137,Hero Extreme,2013,0.65,0.787,16000,Petrol,Individual,Manual,0
138,138,Honda CB Hornet 160R,2016,0.60,0.870,15000,Petrol,Individual,Manual,0
139,139,Bajaj Avenger 220 dtsi,2015,0.60,0.950,16600,Petrol,Individual,Manual,0
140,140,Honda CBR 150,2013,0.60,1.200,32000,Petrol,Individual,Manual,0
141,141,Bajaj Avenger 150 street,2016,0.60,0.800,20000,Petrol,Individual,Manual,0
142,142,Yamaha FZ v 2.0,2015,0.60,0.840,29000,Petrol,Individual,Manual,0
143,143,Yamaha FZ v 2.0,2016,0.60,0.840,25000,Petrol,Individual,Manual,0
144,144,Bajaj Pulsar NS 200,2014,0.60,0.990,25000,Petrol,Individual,Manual,0
145,145,TVS Apache RTR 160,2012,0.60,0.810,19000,Petrol,Individual,Manual,0
146,146,Hero Extreme,2014,0.55,0.787,15000,Petrol,Individual,Manual,0
147,147,Yamaha FZ S V 2.0,2015,0.55,0.840,58000,Petrol,Individual,Manual,0
148,148,Bajaj Pulsar 220 F,2010,0.52,0.940,45000,Petrol,Individual,Manual,0
149,149,Bajaj Pulsar 220 F,2016,0.51,0.940,24000,Petrol,Individual,Manual,0
150,150,TVS Apache RTR 180,2011,0.50,0.826,6000,Petrol,Individual,Manual,0
151,151,Hero Passion X pro,2016,0.50,0.550,31000,Petrol,Individual,Manual,0
152,152,Bajaj Pulsar NS 200,2012,0.50,0.990,13000,Petrol,Individual,Manual,0
153,153,Bajaj Pulsar NS 200,2013,0.50,0.990,45000,Petrol,Individual,Manual,0
154,154,Yamaha Fazer,2014,0.50,0.880,8000,Petrol,Individual,Manual,0
155,155,Honda Activa 4G,2017,0.48,0.510,4300,Petrol,Individual,Automatic,0
156,156,TVS Sport,2017,0.48,0.520,15000,Petrol,Individual,Manual,0
157,157,Yamaha FZ S V 2.0,2015,0.48,0.840,23000,Petrol,Individual,Manual,0
158,158,Honda Dream Yuga,2017,0.48,0.540,8600,Petrol,Individual,Manual,0
159,159,Honda Activa 4G,2017,0.45,0.510,4000,Petrol,Individual,Automatic,0
160,160,Bajaj Avenger Street 220,2011,0.45,0.950,24000,Petrol,Individual,Manual,0
161,161,TVS Apache RTR 180,2014,0.45,0.826,23000,Petrol,Individual,Manual,0
162,162,Bajaj Pulsar NS 200,2012,0.45,0.990,14500,Petrol,Individual,Manual,0
163,163,Bajaj Avenger 220 dtsi,2010,0.45,0.950,27000,Petrol,Individual,Manual,0
164,164,Hero Splender iSmart,2016,0.45,0.540,14000,Petrol,Individual,Manual,0
165,165,Activa 3g,2016,0.45,0.540,500,Petrol,Individual,Automatic,0
166,166,Hero Passion Pro,2016,0.45,0.550,1000,Petrol,Individual,Manual,0
167,167,TVS Apache RTR 160,2014,0.42,0.810,42000,Petrol,Individual,Manual,0
168,168,Honda CB Trigger,2013,0.42,0.730,12000,Petrol,Individual,Manual,0
169,169,Hero Splender iSmart,2015,0.40,0.540,14000,Petrol,Individual,Manual,0
170,170,Yamaha FZ S,2012,0.40,0.830,5500,Petrol,Individual,Manual,0
171,171,Hero Passion Pro,2015,0.40,0.550,6700,Petrol,Individual,Manual,0
172,172,Bajaj Pulsar 135 LS,2014,0.40,0.640,13700,Petrol,Individual,Manual,0
173,173,Activa 4g,2017,0.40,0.510,1300,Petrol,Individual,Automatic,0
174,174,Honda CB Unicorn,2015,0.38,0.720,38600,Petrol,Individual,Manual,0
175,175,Hero Honda CBZ extreme,2011,0.38,0.787,75000,Petrol,Individual,Manual,0
176,176,Honda Karizma,2011,0.35,1.050,30000,Petrol,Individual,Manual,0
177,177,Honda Activa 125,2016,0.35,0.570,24000,Petrol,Individual,Automatic,0
178,178,TVS Jupyter,2014,0.35,0.520,19000,Petrol,Individual,Automatic,0
179,179,Honda Karizma,2010,0.31,1.050,213000,Petrol,Individual,Manual,0
180,180,Hero Honda Passion Pro,2012,0.30,0.510,60000,Petrol,Individual,Manual,0
181,181,Hero Splender Plus,2016,0.30,0.480,50000,Petrol,Individual,Manual,0
182,182,Honda CB Shine,2013,0.30,0.580,30000,Petrol,Individual,Manual,0
183,183,Bajaj Discover 100,2013,0.27,0.470,21000,Petrol,Individual,Manual,0
184,184,Bajaj Pulsar 150,2008,0.25,0.750,26000,Petrol,Individual,Manual,1
185,185,Suzuki Access 125,2008,0.25,0.580,1900,Petrol,Individual,Automatic,0
186,186,TVS Wego,2010,0.25,0.520,22000,Petrol,Individual,Automatic,0
187,187,Honda CB twister,2013,0.25,0.510,32000,Petrol,Individual,Manual,0
188,188,Hero Glamour,2013,0.25,0.570,18000,Petrol,Individual,Manual,0
189,189,Hero Super Splendor,2005,0.20,0.570,55000,Petrol,Individual,Manual,0
190,190,Bajaj Pulsar 150,2008,0.20,0.750,60000,Petrol,Individual,Manual,0
191,191,Bajaj Discover 125,2012,0.20,0.570,25000,Petrol,Individual,Manual,1
192,192,Hero Hunk,2007,0.20,0.750,49000,Petrol,Individual,Manual,1
193,193,Hero Ignitor Disc,2013,0.20,0.650,24000,Petrol,Individual,Manual,1
194,194,Hero CBZ Xtreme,2008,0.20,0.787,50000,Petrol,Individual,Manual,0
195,195,Bajaj ct 100,2015,0.18,0.320,35000,Petrol,Individual,Manual,0
196,196,Activa 3g,2008,0.17,0.520,500000,Petrol,Individual,Automatic,0
197,197,Honda CB twister,2010,0.16,0.510,33000,Petrol,Individual,Manual,0
198,198,Bajaj Discover 125,2011,0.15,0.570,35000,Petrol,Individual,Manual,1
199,199,Honda CB Shine,2007,0.12,0.580,53000,Petrol,Individual,Manual,0
200,200,Bajaj Pulsar 150,2006,0.10,0.750,92233,Petrol,Individual,Manual,0
201,201,i20,2010,3.25,6.790,58000,Diesel,Dealer,Manual,1
202,202,grand i10,2015,4.40,5.700,28200,Petrol,Dealer,Manual,0
203,203,i10,2011,2.95,4.600,53460,Petrol,Dealer,Manual,0
204,204,eon,2015,2.75,4.430,28282,Petrol,Dealer,Manual,0
205,205,grand i10,2016,5.25,5.700,3493,Petrol,Dealer,Manual,1
206,206,xcent,2017,5.75,7.130,12479,Petrol,Dealer,Manual,0
207,207,grand i10,2015,5.15,5.700,34797,Petrol,Dealer,Automatic,0
208,208,i20,2017,7.90,8.100,3435,Petrol,Dealer,Manual,0
209,209,grand i10,2015,4.85,5.700,21125,Diesel,Dealer,Manual,0
210,210,i10,2012,3.10,4.600,35775,Petrol,Dealer,Manual,0
211,211,elantra,2015,11.75,14.790,43535,Diesel,Dealer,Manual,0
212,212,creta,2016,11.25,13.600,22671,Petrol,Dealer,Manual,0
213,213,i20,2011,2.90,6.790,31604,Petrol,Dealer,Manual,0
214,214,grand i10,2017,5.25,5.700,20114,Petrol,Dealer,Manual,0
215,215,verna,2012,4.50,9.400,36100,Petrol,Dealer,Manual,0
216,216,eon,2016,2.90,4.430,12500,Petrol,Dealer,Manual,0
217,217,eon,2016,3.15,4.430,15000,Petrol,Dealer,Manual,0
218,218,verna,2014,6.45,9.400,45078,Petrol,Dealer,Manual,0
219,219,verna,2012,4.50,9.400,36000,Petrol,Dealer,Manual,0
220,220,eon,2017,3.50,4.430,38488,Petrol,Dealer,Manual,0
221,221,i20,2013,4.50,6.790,32000,Petrol,Dealer,Automatic,0
222,222,i20,2014,6.00,7.600,77632,Diesel,Dealer,Manual,0
223,223,verna,2015,8.25,9.400,61381,Diesel,Dealer,Manual,0
224,224,verna,2013,5.11,9.400,36198,Petrol,Dealer,Automatic,0
225,225,i10,2011,2.70,4.600,22517,Petrol,Dealer,Manual,0
226,226,grand i10,2015,5.25,5.700,24678,Petrol,Dealer,Manual,0
227,227,i10,2011,2.55,4.430,57000,Petrol,Dealer,Manual,0
228,228,verna,2012,4.95,9.400,60000,Diesel,Dealer,Manual,0
229,229,i20,2012,3.10,6.790,52132,Diesel,Dealer,Manual,0
230,230,verna,2013,6.15,9.400,45000,Diesel,Dealer,Manual,0
231,231,verna,2017,9.25,9.400,15001,Petrol,Dealer,Manual,0
232,232,elantra,2015,11.45,14.790,12900,Petrol,Dealer,Automatic,0
233,233,grand i10,2013,3.90,5.700,53000,Diesel,Dealer,Manual,0
234,234,grand i10,2015,5.50,5.700,4492,Petrol,Dealer,Manual,0
235,235,verna,2017,9.10,9.400,15141,Petrol,Dealer,Manual,0
236,236,eon,2016,3.10,4.430,11849,Petrol,Dealer,Manual,0
237,237,creta,2015,11.25,13.600,68000,Diesel,Dealer,Manual,0
238,238,verna,2013,4.80,9.400,60241,Petrol,Dealer,Manual,0
239,239,eon,2012,2.00,4.430,23709,Petrol,Dealer,Manual,0
240,240,verna,2012,5.35,9.400,32322,Diesel,Dealer,Manual,0
241,241,xcent,2015,4.75,7.130,35866,Petrol,Dealer,Manual,1
242,242,xcent,2014,4.40,7.130,34000,Petrol,Dealer,Manual,0
243,243,i20,2016,6.25,7.600,7000,Petrol,Dealer,Manual,0
244,244,verna,2013,5.95,9.400,49000,Diesel,Dealer,Manual,0
245,245,verna,2012,5.20,9.400,71000,Diesel,Dealer,Manual,0
246,246,i20,2012,3.75,6.790,35000,Petrol,Dealer,Manual,0
247,247,verna,2015,5.95,9.400,36000,Petrol,Dealer,Manual,0
248,248,i10,2013,4.00,4.600,30000,Petrol,Dealer,Manual,0
249,249,i20,2016,5.25,7.600,17000,Petrol,Dealer,Manual,0
250,250,creta,2016,12.90,13.600,35934,Diesel,Dealer,Manual,0
251,251,city,2013,5.00,9.900,56701,Petrol,Dealer,Manual,0
252,252,brio,2015,5.40,6.820,31427,Petrol,Dealer,Automatic,0
253,253,city,2014,7.20,9.900,48000,Diesel,Dealer,Manual,0
254,254,city,2013,5.25,9.900,54242,Petrol,Dealer,Manual,0
255,255,brio,2012,3.00,5.350,53675,Petrol,Dealer,Manual,0
256,256,city,2016,10.25,13.600,49562,Petrol,Dealer,Manual,0
257,257,city,2015,8.50,13.600,40324,Petrol,Dealer,Manual,0
258,258,city,2015,8.40,13.600,25000,Petrol,Dealer,Manual,0
259,259,amaze,2014,3.90,7.000,36054,Petrol,Dealer,Manual,0
260,260,city,2016,9.15,13.600,29223,Petrol,Dealer,Manual,0
261,261,brio,2016,5.50,5.970,5600,Petrol,Dealer,Manual,0
262,262,amaze,2015,4.00,5.800,40023,Petrol,Dealer,Manual,0
263,263,jazz,2016,6.60,7.700,16002,Petrol,Dealer,Manual,0
264,264,amaze,2015,4.00,7.000,40026,Petrol,Dealer,Manual,0
265,265,jazz,2017,6.50,8.700,21200,Petrol,Dealer,Manual,0
266,266,amaze,2014,3.65,7.000,35000,Petrol,Dealer,Manual,0
267,267,city,2016,8.35,9.400,19434,Diesel,Dealer,Manual,0
268,268,brio,2017,4.80,5.800,19000,Petrol,Dealer,Manual,0
269,269,city,2015,6.70,10.000,18828,Petrol,Dealer,Manual,0
270,270,city,2011,4.10,10.000,69341,Petrol,Dealer,Manual,0
271,271,city,2009,3.00,10.000,69562,Petrol,Dealer,Manual,0
272,272,city,2015,7.50,10.000,27600,Petrol,Dealer,Manual,0
273,273,jazz,2010,2.25,7.500,61203,Petrol,Dealer,Manual,0
274,274,brio,2014,5.30,6.800,16500,Petrol,Dealer,Manual,0
275,275,city,2016,10.90,13.600,30753,Petrol,Dealer,Automatic,0
276,276,city,2015,8.65,13.600,24800,Petrol,Dealer,Manual,0
277,277,city,2015,9.70,13.600,21780,Petrol,Dealer,Manual,0
278,278,jazz,2016,6.00,8.400,4000,Petrol,Dealer,Manual,0
279,279,city,2014,6.25,13.600,40126,Petrol,Dealer,Manual,0
280,280,brio,2015,5.25,5.900,14465,Petrol,Dealer,Manual,0
281,281,city,2006,2.10,7.600,50456,Petrol,Dealer,Manual,0
282,282,city,2014,8.25,14.000,63000,Diesel,Dealer,Manual,0
283,283,city,2016,8.99,11.800,9010,Petrol,Dealer,Manual,0
284,284,brio,2013,3.50,5.900,9800,Petrol,Dealer,Manual,0
285,285,jazz,2016,7.40,8.500,15059,Petrol,Dealer,Automatic,0
286,286,jazz,2016,5.65,7.900,28569,Petrol,Dealer,Manual,0
287,287,amaze,2015,5.75,7.500,44000,Petrol,Dealer,Automatic,0
288,288,city,2015,8.40,13.600,34000,Petrol,Dealer,Manual,0
289,289,city,2016,10.11,13.600,10980,Petrol,Dealer,Manual,0
290,290,amaze,2014,4.50,6.400,19000,Petrol,Dealer,Manual,0
291,291,brio,2015,5.40,6.100,31427,Petrol,Dealer,Manual,0
292,292,jazz,2016,6.40,8.400,12000,Petrol,Dealer,Manual,0
293,293,city,2010,3.25,9.900,38000,Petrol,Dealer,Manual,0
294,294,amaze,2014,3.75,6.800,33019,Petrol,Dealer,Manual,0
295,295,city,2015,8.55,13.090,60076,Diesel,Dealer,Manual,0
296,296,city,2016,9.50,11.600,33988,Diesel,Dealer,Manual,0
297,297,brio,2015,4.00,5.900,60000,Petrol,Dealer,Manual,0
298,298,city,2009,3.35,11.000,87934,Petrol,Dealer,Manual,0
299,299,city,2017,11.50,12.500,9000,Diesel,Dealer,Manual,0
300,300,brio,2016,5.30,5.900,5464,Petrol,Dealer,Manual,0

In [18]:
df.to_excel("output.xlsx")

In [15]:
newParsedDates=pd.read_excel("output.xlsx",parse_dates=[10])

In [16]:
newParsedDatesColumnName=pd.read_excel("output.xlsx",parse_dates=["datesPurchased"])

In [17]:
newParsedDatesColumnName

,Unnamed: 0,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,datePurchased,datesPurchased
0,285,jazz,2016,7.40,8.500,15059,Petrol,Dealer,Automatic,0,10-01-2004,10-01-2004
1,248,i10,2013,4.00,4.600,30000,Petrol,Dealer,Manual,0,11-01-2004,11-01-2004
2,150,TVS Apache RTR 180,2011,0.50,0.826,6000,Petrol,Individual,Manual,0,12-01-2004,12-01-2004
3,217,eon,2016,3.15,4.430,15000,Petrol,Dealer,Manual,0,13-01-2004,13-01-2004
4,107,Royal Enfield Thunder 350,2013,1.25,1.500,15000,Petrol,Individual,Manual,0,14-01-2004,14-01-2004
5,206,xcent,2017,5.75,7.130,12479,Petrol,Dealer,Manual,0,15-01-2004,15-01-2004
6,132,Bajaj Avenger 220,2017,0.75,0.950,3500,Petrol,Individual,Manual,0,16-01-2004,16-01-2004
7,73,etios liva,2011,2.65,5.710,43000,Petrol,Dealer,Manual,0,17-01-2004,17-01-2004
8,288,city,2015,8.40,13.600,34000,Petrol,Dealer,Manual,0,18-01-2004,18-01-2004
9,157,Yamaha FZ S V 2.0,2015,0.48,0.840,23000,Petrol,Individual,Manual,0,19-01-2004,19-01-2004

In [3]:
data={
    "calories": [420,300,390], "duration" : [50,40,45]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       300        40
2       390        45

In [4]:
print(df.loc(0))
print(df.iloc(0))
print(df.loc[0])

<pandas.core.indexing._LocIndexer object at 0x000002B3C9EA9EE0>
<pandas.core.indexing._iLocIndexer object at 0x000002B3C9EA9F80>
calories    420
duration     50
Name: 0, dtype: int64

In [5]:
df.iloc?

Type:        property
String form: <property object at 0x000002B3C990B330>
Docstring:
Purely integer-location based indexing for selection by position.

.. deprecated:: 2.2.0

   Returning a tuple from a callable is deprecated.

``.iloc[]`` is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

Allowed inputs are:

- An integer, e.g. ``5``.
- A list or array of integers, e.g. ``[4, 3, 0]``.
- A slice object with ints, e.g. ``1:7``.
- A boolean array.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above).
  This is useful in method chains, when you don't have a reference to the
  calling object, but would like to base your selection on
  some value.
- A tuple of row and column indexes. The tuple elements consist of one of the
  above inputs, e.g. ``(0, 1)``.

``.iloc`` will raise ``IndexError`` if a requested indexer is
out-of-bounds, except *slice* indexers which allow out-of-bounds
indexing (this conforms with python/numpy *slice* semantics).

See more at :ref:`Selection by Position <indexing.integer>`.

See Also
--------
DataFrame.iat : Fast integer location scalar accessor.
DataFrame.loc : Purely label-location based indexer for selection by label.
Series.iloc : Purely integer-location based indexing for
               selection by position.

Examples
--------
>>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
>>> df = pd.DataFrame(mydict)
>>> df
      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

**Indexing just the rows**

With a scalar integer.

>>> type(df.iloc[0])
<class 'pandas.core.series.Series'>
>>> df.iloc[0]
a    1
b    2
c    3
d    4
Name: 0, dtype: int64

With a list of integers.

>>> df.iloc[[0]]
   a  b  c  d
0  1  2  3  4
>>> type(df.iloc[[0]])
<class 'pandas.core.frame.DataFrame'>

>>> df.iloc[[0, 1]]
     a    b    c    d
0    1    2    3    4
1  100  200  300  400

With a `slice` object.

>>> df.iloc[:3]
      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

With a boolean mask the same length as the index.

>>> df.iloc[[True, False, True]]
      a     b     c     d
0     1     2     3     4
2  1000  2000  3000  4000

With a callable, useful in method chains. The `x` passed
to the ``lambda`` is the DataFrame being sliced. This selects
the rows whose index label even.

>>> df.iloc[lambda x: x.index % 2 == 0]
      a     b     c     d
0     1     2     3     4
2  1000  2000  3000  4000

**Indexing both axes**

You can mix the indexer types for the index and columns. Use ``:`` to
select the entire axis.

With scalar integers.

>>> df.iloc[0, 1]
2

With lists of integers.

>>> df.iloc[[0, 2], [1, 3]]
      b     d
0     2     4
2  2000  4000

With `slice` objects.

>>> df.iloc[1:3, 0:3]
      a     b     c
1   100   200   300
2  1000  2000  3000

With a boolean array whose length matches the columns.

>>> df.iloc[:, [True, False, True, False]]
      a     c
0     1     3
1   100   300
2  1000  3000

With a callable function that expects the Series or DataFrame.

>>> df.iloc[:, lambda df: [0, 2]]
      a     c
0     1     3
1   100   300
2  1000  3000

In [6]:
df.loc?

Type:        property
String form: <property object at 0x000002B3C98DADE0>
Docstring:
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above)

See more at :ref:`Selection by Label <indexing.label>`.

Raises
------
KeyError
    If any items are not found.
IndexingError
    If an indexed key is passed and its index is unalignable to the frame index.

See Also
--------
DataFrame.at : Access a single value for a row/column label pair.
DataFrame.iloc : Access group of rows and columns by integer position(s).
DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
               Series/DataFrame.
Series.loc : Access group of values using labels.

Examples
--------
**Getting values**

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

Single label. Note this returns the row as a Series.

>>> df.loc['viper']
max_speed    4
shield       5
Name: viper, dtype: int64

List of labels. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[['viper', 'sidewinder']]
            max_speed  shield
viper               4       5
sidewinder          7       8

Single label for row and column

>>> df.loc['cobra', 'shield']
2

Slice with labels for row and single label for column. As mentioned
above, note that both the start and stop of the slice are included.

>>> df.loc['cobra':'viper', 'max_speed']
cobra    1
viper    4
Name: max_speed, dtype: int64

Boolean list with the same length as the row axis

>>> df.loc[[False, False, True]]
            max_speed  shield
sidewinder          7       8

Alignable boolean Series:

>>> df.loc[pd.Series([False, True, False],
...                  index=['viper', 'sidewinder', 'cobra'])]
                     max_speed  shield
sidewinder          7       8

Index (same behavior as ``df.reindex``)

>>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
       max_speed  shield
foo
cobra          1       2
viper          4       5

Conditional that returns a boolean Series

>>> df.loc[df['shield'] > 6]
            max_speed  shield
sidewinder          7       8

Conditional that returns a boolean Series with column labels specified

>>> df.loc[df['shield'] > 6, ['max_speed']]
            max_speed
sidewinder          7

Multiple conditional using ``&`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 1) & (df['shield'] < 8)]
            max_speed  shield
viper          4       5

Multiple conditional using ``|`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 4) | (df['shield'] < 5)]
            max_speed  shield
cobra               1       2
sidewinder          7       8

Please ensure that each condition is wrapped in parentheses ``()``.
See the :ref:`user guide<indexing.boolean>`
for more details and explanations of Boolean indexing.

.. note::
    If you find yourself using 3 or more conditionals in ``.loc[]``,
    consider using :ref:`advanced indexing<advanced.advanced_hierarchical>`.

    See below for using ``.loc[]`` on MultiIndex DataFrames.

Callable that returns a boolean Series

>>> df.loc[lambda df: df['shield'] == 8]
            max_speed  shield
sidewinder          7       8

**Setting values**

Set value for all items matching the list of labels

>>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
>>> df
            max_speed  shield
cobra               1       2
viper               4      50
sidewinder          7      50

Set value for an entire row

>>> df.loc['cobra'] = 10
>>> df
            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

Set value for an entire column

>>> df.loc[:, 'max_speed'] = 30
>>> df
            max_speed  shield
cobra              30      10
viper              30      50
sidewinder         30      50

Set value for rows matching callable condition

>>> df.loc[df['shield'] > 35] = 0
>>> df
            max_speed  shield
cobra              30      10
viper               0       0
sidewinder          0       0

Add value matching location

>>> df.loc["viper", "shield"] += 5
>>> df
            max_speed  shield
cobra              30      10
viper               0       5
sidewinder          0       0

Setting using a ``Series`` or a ``DataFrame`` sets the values matching the
index labels, not the index positions.

>>> shuffled_df = df.loc[["viper", "cobra", "sidewinder"]]
>>> df.loc[:] += shuffled_df
>>> df
            max_speed  shield
cobra              60      20
viper               0      10
sidewinder          0       0

**Getting values on a DataFrame with an index that has integer labels**

Another example using integers for the index

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=[7, 8, 9], columns=['max_speed', 'shield'])
>>> df
   max_speed  shield
7          1       2
8          4       5
9          7       8

Slice with integer labels for rows. As mentioned above, note that both
the start and stop of the slice are included.

>>> df.loc[7:9]
   max_speed  shield
7          1       2
8          4       5
9          7       8

**Getting values with a MultiIndex**

A number of examples using a DataFrame with a MultiIndex

>>> tuples = [
...     ('cobra', 'mark i'), ('cobra', 'mark ii'),
...     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
...     ('viper', 'mark ii'), ('viper', 'mark iii')
... ]
>>> index = pd.MultiIndex.from_tuples(tuples)
>>> values = [[12, 2], [0, 4], [10, 20],
...           [1, 4], [7, 1], [16, 36]]
>>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
>>> df
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Single label. Note this returns a DataFrame with a single index.

>>> df.loc['cobra']
         max_speed  shield
mark i          12       2
mark ii          0       4

Single index tuple. Note this returns a Series.

>>> df.loc[('cobra', 'mark ii')]
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

Single label for row and column. Similar to passing in a tuple, this
returns a Series.

>>> df.loc['cobra', 'mark i']
max_speed    12
shield        2
Name: (cobra, mark i), dtype: int64

Single tuple. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[[('cobra', 'mark ii')]]
               max_speed  shield
cobra mark ii          0       4

Single tuple for the index with a single label for the column

>>> df.loc[('cobra', 'mark i'), 'shield']
2

Slice from index tuple to single label

>>> df.loc[('cobra', 'mark i'):'viper']
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Slice from index tuple to index tuple

>>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                    max_speed  shield
cobra      mark i          12       2
           mark ii          0       4
sidewinder mark i          10      20
           mark ii          1       4
viper      mark ii          7       1

Please see the :ref:`user guide<advanced.advanced_hierarchical>`
for more details and explanations of advanced indexing.

In [30]:
print(df.iloc[0,1])
print(df.iloc[2,1])

50
45

In [31]:
print(df.iloc[0:1,0:1])

   calories
0       420

In [37]:
print(df.loc[[0, 1][0]])

calories    420
duration     50
Name: 0, dtype: int64

In [40]:
df.to_json(orient='split')

'{"columns":["calories","duration"],"index":[0,1,2],"data":[[420,50],[300,40],[390,45]]}'

In [45]:
pd.to_json(orient='index')

AttributeError: module 'pandas' has no attribute 'to_json'

In [46]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    "datesPurchased": ["2024-02-03", "2025-04-09", "2023-08-15"],
    "car_model": ["Honda", "Toyota", "Ford"],
    "price": [20000, 25000, 18000]
})

# Convert DataFrame to JSON string with orient='index'
json_str = df.to_json(orient='index')

# Print JSON string
print(json_str)

{"0":{"datesPurchased":"2024-02-03","car_model":"Honda","price":20000},"1":{"datesPurchased":"2025-04-09","car_model":"Toyota","price":25000},"2":{"datesPurchased":"2023-08-15","car_model":"Ford","price":18000}}

In [50]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3

In [52]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("2nd element on the First row:",arr[0,1])

2nd element on the First row: 2

In [54]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print("last element on the second row:",arr[-1,-1])

last element on the second row: 10

In [56]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> import numpy as np
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
       [ 0.]])

>>> s = (2,2)
>>> np.zeros(s)
array([[ 0.,  0.],
       [ 0.,  0.]])

>>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
array([(0, 0), (0, 0)],
      dtype=[('x', '<i4'), ('y', '<i4')])
Type:      builtin_function_or_method

In [57]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.

Examples
--------
>>> import numpy as np
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
       [1.]])

>>> s = (2,2)
>>> np.ones(s)
array([[1.,  1.],
       [1.,  1.]])
File:      c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\numeric.py
Type:      function

In [58]:
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.

Examples
--------
>>> import numpy as np
>>> np.full((2, 2), np.inf)
array([[inf, inf],
       [inf, inf]])
>>> np.full((2, 2), 10)
array([[10, 10],
       [10, 10]])

>>> np.full((2, 2), [1, 2])
array([[1, 2],
       [1, 2]])
File:      c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\numeric.py
Type:      function

In [59]:
np.inf?

Type:        float
String form: inf
Docstring:   Convert a string or number to a floating-point number, if possible.

In [60]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]

In [61]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
print(arr.shape)

(2, 4)

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,12])
newarr = arr.reshape(4,3)
print(newarr)

ValueError: cannot reshape array of size 11 into shape (4,3)

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,3)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]

In [9]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]

In [14]:
mean=(81+85+99+84+87+88+111+86+103+87+94+78+77)/13

print(mean)

89.23076923076923

In [16]:
import numpy 
speed=(81,85,99,84,87,88,111,86,103,87,94,78,77)
x=numpy.median(speed)
print(x)

87.0