# Section A – Basic exploration

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Dataset.csv")
df

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000
5,T0006,2024-01-05,C005,Female,30,Clothing,2,1500,3000
6,T0007,2024-01-06,C006,Female,26,Beauty,4,600,2400
7,T0008,2024-01-06,C007,Male,33,Grocery,10,90,900
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000
9,T0010,2024-01-07,C009,Female,24,Clothing,5,900,4500
10,T0011,2024-01-08,C010,Male,31,Sports,2,2500,5000
11,T0012,2024-01-08,C011,Female,29,Beauty,3,700,2100
12,T0013,2024-01-09,C012,Female,41,Furniture,1,22000,22000
13,T0014,2024-01-09,C002,Female,35,Grocery,8,95,760
14,T0015,2024-01-10,C003,Female,22,Clothing,2,1100,2200
15,T0016,2024-01-10,C004,Male,42,Electronics,1,38000,38000
16,T0017,2024-01-11,C005,Female,30,Home Decor,3,1600,4800
17,T0018,2024-01-11,C006,Female,26,Grocery,12,85,1020
18,T0019,2024-01-12,C007,Male,33,Sports,1,3200,3200
19,T0020,2024-01-12,C008,Male,39,Clothing,4,1300,5200
20,T0021,2024-01-13,C009,Female,24,Beauty,6,550,3300
21,T0022,2024-01-13,C010,Male,31,Electronics,1,41000,41000
22,T0023,2024-01-14,C011,Female,29,Home Decor,2,1900,3800
23,T0024,2024-01-14,C012,Female,41,Grocery,20,70,1400
24,T0025,2024-01-15,C001,Male,28,Clothing,1,1500,1500
25,T0026,2024-01-15,C002,Female,35,Furniture,1,25000,25000
26,T0027,2024-01-16,C003,Female,22,Beauty,2,800,1600
27,T0028,2024-01-16,C004,Male,42,Sports,1,2800,2800
28,T0029,2024-01-17,C005,Female,30,Grocery,18,75,1350
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000
30,T0031,2024-01-18,C007,Male,33,Home Decor,4,1400,5600
31,T0032,2024-01-18,C008,Male,39,Clothing,3,1250,3750
32,T0033,2024-01-19,C009,Female,24,Grocery,9,85,765
33,T0034,2024-01-19,C010,Male,31,Furniture,1,19500,19500
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000
35,T0036,2024-01-20,C012,Female,41,Beauty,5,650,3250
36,T0037,2024-01-21,C001,Male,28,Grocery,14,80,1120
37,T0038,2024-01-21,C002,Female,35,Clothing,4,1400,5600
38,T0039,2024-01-22,C003,Female,22,Home Decor,2,1700,3400
39,T0040,2024-01-22,C004,Male,42,Sports,3,2600,7800
40,T0041,2024-01-23,C005,Female,30,Furniture,1,23000,23000
41,T0042,2024-01-23,C006,Female,26,Clothing,2,1350,2700
42,T0043,2024-01-24,C007,Male,33,Electronics,1,37000,37000
43,T0044,2024-01-24,C008,Male,39,Beauty,4,720,2880
44,T0045,2024-01-25,C009,Female,24,Grocery,11,90,990
45,T0046,2024-01-25,C010,Male,31,Home Decor,3,1500,4500
46,T0047,2024-01-26,C011,Female,29,Clothing,5,1000,5000
47,T0048,2024-01-26,C012,Female,41,Sports,2,3000,6000
48,T0049,2024-01-27,C001,Male,28,Furniture,1,21000,21000
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000

## How many rows and columns are there in the dataset?

In [3]:
df.shape

(50, 9)

## What are the data types of each column?

In [7]:
df.dtypes

TransactionID      object
Date               object
CustomerID         object
Gender             object
Age                 int64
ProductCategory    object
Quantity            int64
PricePerUnit        int64
TotalAmount         int64
dtype: object

## Are there any missing values in each column? If yes, how many?

In [9]:
df.isnull().sum()

TransactionID      0
Date               0
CustomerID         0
Gender             0
Age                0
ProductCategory    0
Quantity           0
PricePerUnit       0
TotalAmount        0
dtype: int64

## What is the minimum, maximum, mean, and median of Age, Quantity, PricePerUnit, and TotalAmount?

In [12]:
df[["Age","Quantity","PricePerUnit","TotalAmount"]].describe()

            Age   Quantity  PricePerUnit   TotalAmount
count  50.00000  50.000000      50.00000     50.000000
mean   31.66000   4.220000   10549.40000  11969.700000
std     6.22572   4.656748   16618.87259  15854.011094
min    22.00000   1.000000      70.00000    760.000000
25%    28.00000   1.000000     705.00000   2250.000000
50%    30.50000   2.000000    1500.00000   3775.000000
75%    35.00000   4.750000   19125.00000  19125.000000
max    42.00000  20.000000   52000.00000  52000.000000

## How many unique customers and unique product categories are there?

In [14]:
df["CustomerID"].nunique()

12

In [15]:
df["ProductCategory"].nunique()

7

# Section B – Revenue and product analysis

## What is the total revenue (sum of TotalAmount) in the dataset?

In [18]:
df['TotalAmount'].sum()

np.int64(598485)

## Which three product categories generate the highest total revenue?

In [4]:
df.groupby('ProductCategory')['TotalAmount'].sum().sort_values(ascending=False).head(3)

ProductCategory
Electronics    361000
Furniture      128500
Clothing        37050
Name: TotalAmount, dtype: int64

# For each ProductCategory, what are the:
## Total revenue

In [5]:
df.groupby('ProductCategory')['TotalAmount'].sum()

ProductCategory
Beauty          15530
Clothing        37050
Electronics    361000
Furniture      128500
Grocery          9505
Home Decor      22100
Sports          24800
Name: TotalAmount, dtype: int64

## Average revenue per transaction

In [6]:
df.groupby('TransactionID')['TotalAmount'].mean()

TransactionID
T0001    45000.0
T0002     3600.0
T0003     1200.0
T0004     3000.0
T0005    18000.0
T0006     3000.0
T0007     2400.0
T0008      900.0
T0009    52000.0
T0010     4500.0
T0011     5000.0
T0012     2100.0
T0013    22000.0
T0014      760.0
T0015     2200.0
T0016    38000.0
T0017     4800.0
T0018     1020.0
T0019     3200.0
T0020     5200.0
T0021     3300.0
T0022    41000.0
T0023     3800.0
T0024     1400.0
T0025     1500.0
T0026    25000.0
T0027     1600.0
T0028     2800.0
T0029     1350.0
T0030    46000.0
T0031     5600.0
T0032     3750.0
T0033      765.0
T0034    19500.0
T0035    50000.0
T0036     3250.0
T0037     1120.0
T0038     5600.0
T0039     3400.0
T0040     7800.0
T0041    23000.0
T0042     2700.0
T0043    37000.0
T0044     2880.0
T0045      990.0
T0046     4500.0
T0047     5000.0
T0048     6000.0
T0049    21000.0
T0050    49000.0
Name: TotalAmount, dtype: float64

## Total quantity sold

In [31]:
df['Quantity'].sum()

np.int64(211)

## Which ProductCategory has the highest average PricePerUnit?

In [9]:
df.groupby('ProductCategory')['PricePerUnit'].sum().sort_values(ascending=False).head(10)

ProductCategory
Electronics    359500
Furniture      128500
Sports          14100
Clothing        12500
Home Decor       8100
Beauty           4020
Grocery           750
Name: PricePerUnit, dtype: int64

## Section C – Customer and segment analysis

## Create age groups: <18, 18–25, 26–35, 36–50, 50+.

In [10]:
bins=[0,18,25,35,50,100]
labels=["<18","18-25","26-35","36-50","50+"]
df['AgeGroup']=pd.cut(df['Age'],bins=bins,labels=labels)

In [11]:
df

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600,26-35
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200,18-25
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000,26-35
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000,36-50
5,T0006,2024-01-05,C005,Female,30,Clothing,2,1500,3000,26-35
6,T0007,2024-01-06,C006,Female,26,Beauty,4,600,2400,26-35
7,T0008,2024-01-06,C007,Male,33,Grocery,10,90,900,26-35
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000,36-50
9,T0010,2024-01-07,C009,Female,24,Clothing,5,900,4500,18-25
10,T0011,2024-01-08,C010,Male,31,Sports,2,2500,5000,26-35
11,T0012,2024-01-08,C011,Female,29,Beauty,3,700,2100,26-35
12,T0013,2024-01-09,C012,Female,41,Furniture,1,22000,22000,36-50
13,T0014,2024-01-09,C002,Female,35,Grocery,8,95,760,26-35
14,T0015,2024-01-10,C003,Female,22,Clothing,2,1100,2200,18-25
15,T0016,2024-01-10,C004,Male,42,Electronics,1,38000,38000,36-50
16,T0017,2024-01-11,C005,Female,30,Home Decor,3,1600,4800,26-35
17,T0018,2024-01-11,C006,Female,26,Grocery,12,85,1020,26-35
18,T0019,2024-01-12,C007,Male,33,Sports,1,3200,3200,26-35
19,T0020,2024-01-12,C008,Male,39,Clothing,4,1300,5200,36-50
20,T0021,2024-01-13,C009,Female,24,Beauty,6,550,3300,18-25
21,T0022,2024-01-13,C010,Male,31,Electronics,1,41000,41000,26-35
22,T0023,2024-01-14,C011,Female,29,Home Decor,2,1900,3800,26-35
23,T0024,2024-01-14,C012,Female,41,Grocery,20,70,1400,36-50
24,T0025,2024-01-15,C001,Male,28,Clothing,1,1500,1500,26-35
25,T0026,2024-01-15,C002,Female,35,Furniture,1,25000,25000,26-35
26,T0027,2024-01-16,C003,Female,22,Beauty,2,800,1600,18-25
27,T0028,2024-01-16,C004,Male,42,Sports,1,2800,2800,36-50
28,T0029,2024-01-17,C005,Female,30,Grocery,18,75,1350,26-35
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000,26-35
30,T0031,2024-01-18,C007,Male,33,Home Decor,4,1400,5600,26-35
31,T0032,2024-01-18,C008,Male,39,Clothing,3,1250,3750,36-50
32,T0033,2024-01-19,C009,Female,24,Grocery,9,85,765,18-25
33,T0034,2024-01-19,C010,Male,31,Furniture,1,19500,19500,26-35
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000,26-35
35,T0036,2024-01-20,C012,Female,41,Beauty,5,650,3250,36-50
36,T0037,2024-01-21,C001,Male,28,Grocery,14,80,1120,26-35
37,T0038,2024-01-21,C002,Female,35,Clothing,4,1400,5600,26-35
38,T0039,2024-01-22,C003,Female,22,Home Decor,2,1700,3400,18-25
39,T0040,2024-01-22,C004,Male,42,Sports,3,2600,7800,36-50
40,T0041,2024-01-23,C005,Female,30,Furniture,1,23000,23000,26-35
41,T0042,2024-01-23,C006,Female,26,Clothing,2,1350,2700,26-35
42,T0043,2024-01-24,C007,Male,33,Electronics,1,37000,37000,26-35
43,T0044,2024-01-24,C008,Male,39,Beauty,4,720,2880,36-50
44,T0045,2024-01-25,C009,Female,24,Grocery,11,90,990,18-25
45,T0046,2024-01-25,C010,Male,31,Home Decor,3,1500,4500,26-35
46,T0047,2024-01-26,C011,Female,29,Clothing,5,1000,5000,26-35
47,T0048,2024-01-26,C012,Female,41,Sports,2,3000,6000,36-50
48,T0049,2024-01-27,C001,Male,28,Furniture,1,21000,21000,26-35
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000,26-35

# For each age group, compute:
## Number of customers

In [12]:
df.groupby('AgeGroup')['CustomerID'].nunique()

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15492\3141711418.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('AgeGroup')['CustomerID'].nunique()

AgeGroup
<18      0
18-25    2
26-35    7
36-50    3
50+      0
Name: CustomerID, dtype: int64

## Total revenue

In [13]:
df['TotalAmount'].sum()

np.int64(598485)

## Average TotalAmount per transaction

In [14]:
df1=df.groupby('TransactionID')['TotalAmount'].mean()

df1

## For each combination of AgeGroup and Gender, compute:

### Total revenue

### Average TotalAmount

### Which segment (AgeGroup × Gender) is most valuable?

### Identify the top 10 customers by total revenue.

### For the top 10 customers, what is their:

### Average order value (TotalAmount per transaction)

### Average quantity per transaction

In [16]:
df.groupby(["AgeGroup","Gender"]).agg(
    Total_Revenue=("TotalAmount","sum"),
    Avg_TotalAmount=("TotalAmount","mean")
)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15492\3148585061.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["AgeGroup","Gender"]).agg(

                 Total_Revenue  Avg_TotalAmount
AgeGroup Gender
<18      Female              0              NaN
         Male                0              NaN
18-25    Female          17955      2244.375000
         Male                0              NaN
26-35    Female         229130     13478.235294
         Male           188320     14486.153846
36-50    Female          32650      8162.500000
         Male           130430     16303.750000
50+      Female              0              NaN
         Male                0              NaN

In [17]:
df.groupby(['AgeGroup','Gender'])['TotalAmount'].sum().sort_values(ascending=False)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15492\1287586835.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['AgeGroup','Gender'])['TotalAmount'].sum().sort_values(ascending=False)

AgeGroup  Gender
26-35     Female    229130
          Male      188320
36-50     Male      130430
          Female     32650
18-25     Female     17955
<18       Female         0
          Male           0
18-25     Male           0
50+       Female         0
          Male           0
Name: TotalAmount, dtype: int64

In [20]:
df3=df.groupby('CustomerID')['TotalAmount'].sum().sort_values(ascending=False).head(10)
df3

CustomerID
C002    83960
C001    71620
C010    70000
C004    66600
C008    63830
C011    60900
C006    52120
C007    46700
C012    32650
C005    32150
Name: TotalAmount, dtype: int64

In [24]:
top_10=df3.index
top_10

Index(['C002', 'C001', 'C010', 'C004', 'C008', 'C011', 'C006', 'C007', 'C012',
       'C005'],
      dtype='object', name='CustomerID')

In [27]:
df4=df[df['CustomerID'].isin(top_10)].groupby('CustomerID').agg(Average_TotalAmount=("TotalAmount","mean"),
                                  Average_Quantity=("Quantity","mean")
                                 )

In [28]:
df4

            Average_TotalAmount  Average_Quantity
CustomerID
C001                    14324.0              3.80
C002                    16792.0              3.40
C004                    16650.0              1.50
C005                     8037.5              6.00
C006                    13030.0              4.75
C007                    11675.0              4.00
C008                    15957.5              3.00
C010                    17500.0              1.75
C011                    15225.0              2.75
C012                     8162.5              7.00

Section D – Time‑based analysis
Convert Date to proper datetime and extract:

Year

Month

Day of week

For each month, compute:

Total revenue

Number of transactions

Average TotalAmount per transaction

On which day of the week is revenue highest on average?

Identify any months where both:

Total revenue is above the overall monthly average

Number of transactions is also above the overall monthly average

In [31]:
df['Year']=df['Date'].dt.year
df

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup,Year
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35,2024
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600,26-35,2024
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200,18-25,2024
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000,26-35,2024
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000,36-50,2024
5,T0006,2024-01-05,C005,Female,30,Clothing,2,1500,3000,26-35,2024
6,T0007,2024-01-06,C006,Female,26,Beauty,4,600,2400,26-35,2024
7,T0008,2024-01-06,C007,Male,33,Grocery,10,90,900,26-35,2024
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000,36-50,2024
9,T0010,2024-01-07,C009,Female,24,Clothing,5,900,4500,18-25,2024
10,T0011,2024-01-08,C010,Male,31,Sports,2,2500,5000,26-35,2024
11,T0012,2024-01-08,C011,Female,29,Beauty,3,700,2100,26-35,2024
12,T0013,2024-01-09,C012,Female,41,Furniture,1,22000,22000,36-50,2024
13,T0014,2024-01-09,C002,Female,35,Grocery,8,95,760,26-35,2024
14,T0015,2024-01-10,C003,Female,22,Clothing,2,1100,2200,18-25,2024
15,T0016,2024-01-10,C004,Male,42,Electronics,1,38000,38000,36-50,2024
16,T0017,2024-01-11,C005,Female,30,Home Decor,3,1600,4800,26-35,2024
17,T0018,2024-01-11,C006,Female,26,Grocery,12,85,1020,26-35,2024
18,T0019,2024-01-12,C007,Male,33,Sports,1,3200,3200,26-35,2024
19,T0020,2024-01-12,C008,Male,39,Clothing,4,1300,5200,36-50,2024
20,T0021,2024-01-13,C009,Female,24,Beauty,6,550,3300,18-25,2024
21,T0022,2024-01-13,C010,Male,31,Electronics,1,41000,41000,26-35,2024
22,T0023,2024-01-14,C011,Female,29,Home Decor,2,1900,3800,26-35,2024
23,T0024,2024-01-14,C012,Female,41,Grocery,20,70,1400,36-50,2024
24,T0025,2024-01-15,C001,Male,28,Clothing,1,1500,1500,26-35,2024
25,T0026,2024-01-15,C002,Female,35,Furniture,1,25000,25000,26-35,2024
26,T0027,2024-01-16,C003,Female,22,Beauty,2,800,1600,18-25,2024
27,T0028,2024-01-16,C004,Male,42,Sports,1,2800,2800,36-50,2024
28,T0029,2024-01-17,C005,Female,30,Grocery,18,75,1350,26-35,2024
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000,26-35,2024
30,T0031,2024-01-18,C007,Male,33,Home Decor,4,1400,5600,26-35,2024
31,T0032,2024-01-18,C008,Male,39,Clothing,3,1250,3750,36-50,2024
32,T0033,2024-01-19,C009,Female,24,Grocery,9,85,765,18-25,2024
33,T0034,2024-01-19,C010,Male,31,Furniture,1,19500,19500,26-35,2024
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000,26-35,2024
35,T0036,2024-01-20,C012,Female,41,Beauty,5,650,3250,36-50,2024
36,T0037,2024-01-21,C001,Male,28,Grocery,14,80,1120,26-35,2024
37,T0038,2024-01-21,C002,Female,35,Clothing,4,1400,5600,26-35,2024
38,T0039,2024-01-22,C003,Female,22,Home Decor,2,1700,3400,18-25,2024
39,T0040,2024-01-22,C004,Male,42,Sports,3,2600,7800,36-50,2024
40,T0041,2024-01-23,C005,Female,30,Furniture,1,23000,23000,26-35,2024
41,T0042,2024-01-23,C006,Female,26,Clothing,2,1350,2700,26-35,2024
42,T0043,2024-01-24,C007,Male,33,Electronics,1,37000,37000,26-35,2024
43,T0044,2024-01-24,C008,Male,39,Beauty,4,720,2880,36-50,2024
44,T0045,2024-01-25,C009,Female,24,Grocery,11,90,990,18-25,2024
45,T0046,2024-01-25,C010,Male,31,Home Decor,3,1500,4500,26-35,2024
46,T0047,2024-01-26,C011,Female,29,Clothing,5,1000,5000,26-35,2024
47,T0048,2024-01-26,C012,Female,41,Sports,2,3000,6000,36-50,2024
48,T0049,2024-01-27,C001,Male,28,Furniture,1,21000,21000,26-35,2024
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000,26-35,2024

In [32]:
df['Month']=df['Date'].dt.month
df

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup,Year,Month
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35,2024,1
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600,26-35,2024,1
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200,18-25,2024,1
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000,26-35,2024,1
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000,36-50,2024,1
5,T0006,2024-01-05,C005,Female,30,Clothing,2,1500,3000,26-35,2024,1
6,T0007,2024-01-06,C006,Female,26,Beauty,4,600,2400,26-35,2024,1
7,T0008,2024-01-06,C007,Male,33,Grocery,10,90,900,26-35,2024,1
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000,36-50,2024,1
9,T0010,2024-01-07,C009,Female,24,Clothing,5,900,4500,18-25,2024,1
10,T0011,2024-01-08,C010,Male,31,Sports,2,2500,5000,26-35,2024,1
11,T0012,2024-01-08,C011,Female,29,Beauty,3,700,2100,26-35,2024,1
12,T0013,2024-01-09,C012,Female,41,Furniture,1,22000,22000,36-50,2024,1
13,T0014,2024-01-09,C002,Female,35,Grocery,8,95,760,26-35,2024,1
14,T0015,2024-01-10,C003,Female,22,Clothing,2,1100,2200,18-25,2024,1
15,T0016,2024-01-10,C004,Male,42,Electronics,1,38000,38000,36-50,2024,1
16,T0017,2024-01-11,C005,Female,30,Home Decor,3,1600,4800,26-35,2024,1
17,T0018,2024-01-11,C006,Female,26,Grocery,12,85,1020,26-35,2024,1
18,T0019,2024-01-12,C007,Male,33,Sports,1,3200,3200,26-35,2024,1
19,T0020,2024-01-12,C008,Male,39,Clothing,4,1300,5200,36-50,2024,1
20,T0021,2024-01-13,C009,Female,24,Beauty,6,550,3300,18-25,2024,1
21,T0022,2024-01-13,C010,Male,31,Electronics,1,41000,41000,26-35,2024,1
22,T0023,2024-01-14,C011,Female,29,Home Decor,2,1900,3800,26-35,2024,1
23,T0024,2024-01-14,C012,Female,41,Grocery,20,70,1400,36-50,2024,1
24,T0025,2024-01-15,C001,Male,28,Clothing,1,1500,1500,26-35,2024,1
25,T0026,2024-01-15,C002,Female,35,Furniture,1,25000,25000,26-35,2024,1
26,T0027,2024-01-16,C003,Female,22,Beauty,2,800,1600,18-25,2024,1
27,T0028,2024-01-16,C004,Male,42,Sports,1,2800,2800,36-50,2024,1
28,T0029,2024-01-17,C005,Female,30,Grocery,18,75,1350,26-35,2024,1
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000,26-35,2024,1
30,T0031,2024-01-18,C007,Male,33,Home Decor,4,1400,5600,26-35,2024,1
31,T0032,2024-01-18,C008,Male,39,Clothing,3,1250,3750,36-50,2024,1
32,T0033,2024-01-19,C009,Female,24,Grocery,9,85,765,18-25,2024,1
33,T0034,2024-01-19,C010,Male,31,Furniture,1,19500,19500,26-35,2024,1
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000,26-35,2024,1
35,T0036,2024-01-20,C012,Female,41,Beauty,5,650,3250,36-50,2024,1
36,T0037,2024-01-21,C001,Male,28,Grocery,14,80,1120,26-35,2024,1
37,T0038,2024-01-21,C002,Female,35,Clothing,4,1400,5600,26-35,2024,1
38,T0039,2024-01-22,C003,Female,22,Home Decor,2,1700,3400,18-25,2024,1
39,T0040,2024-01-22,C004,Male,42,Sports,3,2600,7800,36-50,2024,1
40,T0041,2024-01-23,C005,Female,30,Furniture,1,23000,23000,26-35,2024,1
41,T0042,2024-01-23,C006,Female,26,Clothing,2,1350,2700,26-35,2024,1
42,T0043,2024-01-24,C007,Male,33,Electronics,1,37000,37000,26-35,2024,1
43,T0044,2024-01-24,C008,Male,39,Beauty,4,720,2880,36-50,2024,1
44,T0045,2024-01-25,C009,Female,24,Grocery,11,90,990,18-25,2024,1
45,T0046,2024-01-25,C010,Male,31,Home Decor,3,1500,4500,26-35,2024,1
46,T0047,2024-01-26,C011,Female,29,Clothing,5,1000,5000,26-35,2024,1
47,T0048,2024-01-26,C012,Female,41,Sports,2,3000,6000,36-50,2024,1
48,T0049,2024-01-27,C001,Male,28,Furniture,1,21000,21000,26-35,2024,1
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000,26-35,2024,1

In [34]:
df['DayOfWeek']=df['Date'].dt.day_name()
df

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup,Year,Month,DayOfWeek
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35,2024,1,Wednesday
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600,26-35,2024,1,Wednesday
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200,18-25,2024,1,Thursday
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000,26-35,2024,1,Thursday
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000,36-50,2024,1,Friday
5,T0006,2024-01-05,C005,Female,30,Clothing,2,1500,3000,26-35,2024,1,Friday
6,T0007,2024-01-06,C006,Female,26,Beauty,4,600,2400,26-35,2024,1,Saturday
7,T0008,2024-01-06,C007,Male,33,Grocery,10,90,900,26-35,2024,1,Saturday
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000,36-50,2024,1,Sunday
9,T0010,2024-01-07,C009,Female,24,Clothing,5,900,4500,18-25,2024,1,Sunday
10,T0011,2024-01-08,C010,Male,31,Sports,2,2500,5000,26-35,2024,1,Monday
11,T0012,2024-01-08,C011,Female,29,Beauty,3,700,2100,26-35,2024,1,Monday
12,T0013,2024-01-09,C012,Female,41,Furniture,1,22000,22000,36-50,2024,1,Tuesday
13,T0014,2024-01-09,C002,Female,35,Grocery,8,95,760,26-35,2024,1,Tuesday
14,T0015,2024-01-10,C003,Female,22,Clothing,2,1100,2200,18-25,2024,1,Wednesday
15,T0016,2024-01-10,C004,Male,42,Electronics,1,38000,38000,36-50,2024,1,Wednesday
16,T0017,2024-01-11,C005,Female,30,Home Decor,3,1600,4800,26-35,2024,1,Thursday
17,T0018,2024-01-11,C006,Female,26,Grocery,12,85,1020,26-35,2024,1,Thursday
18,T0019,2024-01-12,C007,Male,33,Sports,1,3200,3200,26-35,2024,1,Friday
19,T0020,2024-01-12,C008,Male,39,Clothing,4,1300,5200,36-50,2024,1,Friday
20,T0021,2024-01-13,C009,Female,24,Beauty,6,550,3300,18-25,2024,1,Saturday
21,T0022,2024-01-13,C010,Male,31,Electronics,1,41000,41000,26-35,2024,1,Saturday
22,T0023,2024-01-14,C011,Female,29,Home Decor,2,1900,3800,26-35,2024,1,Sunday
23,T0024,2024-01-14,C012,Female,41,Grocery,20,70,1400,36-50,2024,1,Sunday
24,T0025,2024-01-15,C001,Male,28,Clothing,1,1500,1500,26-35,2024,1,Monday
25,T0026,2024-01-15,C002,Female,35,Furniture,1,25000,25000,26-35,2024,1,Monday
26,T0027,2024-01-16,C003,Female,22,Beauty,2,800,1600,18-25,2024,1,Tuesday
27,T0028,2024-01-16,C004,Male,42,Sports,1,2800,2800,36-50,2024,1,Tuesday
28,T0029,2024-01-17,C005,Female,30,Grocery,18,75,1350,26-35,2024,1,Wednesday
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000,26-35,2024,1,Wednesday
30,T0031,2024-01-18,C007,Male,33,Home Decor,4,1400,5600,26-35,2024,1,Thursday
31,T0032,2024-01-18,C008,Male,39,Clothing,3,1250,3750,36-50,2024,1,Thursday
32,T0033,2024-01-19,C009,Female,24,Grocery,9,85,765,18-25,2024,1,Friday
33,T0034,2024-01-19,C010,Male,31,Furniture,1,19500,19500,26-35,2024,1,Friday
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000,26-35,2024,1,Saturday
35,T0036,2024-01-20,C012,Female,41,Beauty,5,650,3250,36-50,2024,1,Saturday
36,T0037,2024-01-21,C001,Male,28,Grocery,14,80,1120,26-35,2024,1,Sunday
37,T0038,2024-01-21,C002,Female,35,Clothing,4,1400,5600,26-35,2024,1,Sunday
38,T0039,2024-01-22,C003,Female,22,Home Decor,2,1700,3400,18-25,2024,1,Monday
39,T0040,2024-01-22,C004,Male,42,Sports,3,2600,7800,36-50,2024,1,Monday
40,T0041,2024-01-23,C005,Female,30,Furniture,1,23000,23000,26-35,2024,1,Tuesday
41,T0042,2024-01-23,C006,Female,26,Clothing,2,1350,2700,26-35,2024,1,Tuesday
42,T0043,2024-01-24,C007,Male,33,Electronics,1,37000,37000,26-35,2024,1,Wednesday
43,T0044,2024-01-24,C008,Male,39,Beauty,4,720,2880,36-50,2024,1,Wednesday
44,T0045,2024-01-25,C009,Female,24,Grocery,11,90,990,18-25,2024,1,Thursday
45,T0046,2024-01-25,C010,Male,31,Home Decor,3,1500,4500,26-35,2024,1,Thursday
46,T0047,2024-01-26,C011,Female,29,Clothing,5,1000,5000,26-35,2024,1,Friday
47,T0048,2024-01-26,C012,Female,41,Sports,2,3000,6000,36-50,2024,1,Friday
48,T0049,2024-01-27,C001,Male,28,Furniture,1,21000,21000,26-35,2024,1,Saturday
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000,26-35,2024,1,Saturday

In [35]:
monthly=df.groupby('Month').agg(TotalRevenue=('TotalAmount','sum'),NumberofTransactions=('TransactionID','count'),AverageRevenue=('TotalAmount','mean'))

In [36]:
monthly

       TotalRevenue  NumberofTransactions  AverageRevenue
Month
1            598485                    50         11969.7

In [39]:
top_revenue=df.groupby('DayOfWeek')['TotalAmount'].mean().sort_values(ascending=False).idxmax()
top_revenue

'Wednesday'

In [43]:
avg_revenue = monthly['TotalRevenue'].mean()
avg_revenue

np.float64(598485.0)

In [44]:
avg_transactions = monthly['NumberofTransactions'].mean()
avg_transactions

np.float64(50.0)

In [50]:
filtered_month=monthly[(monthly['TotalRevenue']>avg_revenue)|( monthly['NumberofTransactions']>avg_transactions)]
filtered_month

Empty DataFrame
Columns: [TotalRevenue, NumberofTransactions, AverageRevenue]
Index: []

# Section E – NumPy‑focused tasks
## Using NumPy arrays, compute the:

## Mean, standard deviation, and 25th/50th/75th percentiles of TotalAmount

## Implement a z‑score normalization of TotalAmount using NumPy and add it as a new column AmountZ. Which transactions have AmountZ > 2 (high‑value outliers)?

## Using NumPy only (no Pandas groupby), compute the overall average order value (mean TotalAmount per TransactionID).

## Using NumPy boolean indexing, create an array of TotalAmount values where ProductCategory == "Electronics" and compute mean and standard deviation for this subset.

In [51]:
amount=df['TotalAmount'].values
amount

array([45000,  3600,  1200,  3000, 18000,  3000,  2400,   900, 52000,
        4500,  5000,  2100, 22000,   760,  2200, 38000,  4800,  1020,
        3200,  5200,  3300, 41000,  3800,  1400,  1500, 25000,  1600,
        2800,  1350, 46000,  5600,  3750,   765, 19500, 50000,  3250,
        1120,  5600,  3400,  7800, 23000,  2700, 37000,  2880,   990,
        4500,  5000,  6000, 21000, 49000])

In [58]:
mean=np.mean(amount)
mean

np.float64(11969.7)

In [59]:
std=np.std(amount)
std

np.float64(15694.670254898636)

In [61]:
median=np.median(amount)
median

np.float64(3775.0)

In [62]:
p50=np.percentile(amount,50)
p50

np.float64(3775.0)

In [63]:
p25=np.percentile(amount,25)
p25

np.float64(2250.0)

In [64]:
p75=np.percentile(amount,75)
p75

np.float64(19125.0)

In [65]:
z_score=(amount-mean)/std
z_score

array([ 2.10455521, -0.53328295, -0.6862011 , -0.57151249,  0.38422598,
       -0.57151249, -0.60974202, -0.70531587,  2.55056649, -0.47593864,
       -0.44408069, -0.62885679,  0.63908957, -0.7142361 , -0.6224852 ,
        1.65854392, -0.45682387, -0.69766996, -0.55876931, -0.43133751,
       -0.55239772,  1.84969162, -0.52053977, -0.67345792, -0.66708633,
        0.83023726, -0.66071474, -0.58425566, -0.67664372,  2.1682711 ,
       -0.40585115, -0.52372556, -0.71391752,  0.47979982,  2.42313469,
       -0.55558351, -0.69129837, -0.40585115, -0.54602613, -0.26567618,
        0.70280546, -0.59062725,  1.59482803, -0.57915839, -0.69958144,
       -0.47593864, -0.44408069, -0.38036479,  0.57537367,  2.3594188 ])

In [69]:
df['AmountZ']=z_score
df.head()

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup,Year,Month,DayOfWeek,AmountZ
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35,2024,1,Wednesday,2.104555
1,T0002,2024-01-03,C002,Female,35,Clothing,3,1200,3600,26-35,2024,1,Wednesday,-0.533283
2,T0003,2024-01-04,C003,Female,22,Grocery,15,80,1200,18-25,2024,1,Thursday,-0.686201
3,T0004,2024-01-04,C001,Male,28,Electronics,2,1500,3000,26-35,2024,1,Thursday,-0.571512
4,T0005,2024-01-05,C004,Male,42,Furniture,1,18000,18000,36-50,2024,1,Friday,0.384226

In [68]:
outlier=df[df['AmountZ']>2]
outlier

,TransactionID,Date,CustomerID,Gender,Age,ProductCategory,Quantity,PricePerUnit,TotalAmount,AgeGroup,Year,Month,DayOfWeek,AmountZ
0,T0001,2024-01-03,C001,Male,28,Electronics,1,45000,45000,26-35,2024,1,Wednesday,2.104555
8,T0009,2024-01-07,C008,Male,39,Electronics,1,52000,52000,36-50,2024,1,Sunday,2.550566
29,T0030,2024-01-17,C006,Female,26,Electronics,1,46000,46000,26-35,2024,1,Wednesday,2.168271
34,T0035,2024-01-20,C011,Female,29,Electronics,1,50000,50000,26-35,2024,1,Saturday,2.423135
49,T0050,2024-01-27,C002,Female,35,Electronics,1,49000,49000,26-35,2024,1,Saturday,2.359419

In [71]:
transaction=df['TransactionID'].values
transaction

array(['T0001', 'T0002', 'T0003', 'T0004', 'T0005', 'T0006', 'T0007',
       'T0008', 'T0009', 'T0010', 'T0011', 'T0012', 'T0013', 'T0014',
       'T0015', 'T0016', 'T0017', 'T0018', 'T0019', 'T0020', 'T0021',
       'T0022', 'T0023', 'T0024', 'T0025', 'T0026', 'T0027', 'T0028',
       'T0029', 'T0030', 'T0031', 'T0032', 'T0033', 'T0034', 'T0035',
       'T0036', 'T0037', 'T0038', 'T0039', 'T0040', 'T0041', 'T0042',
       'T0043', 'T0044', 'T0045', 'T0046', 'T0047', 'T0048', 'T0049',
       'T0050'], dtype=object)

In [73]:
unique=np.unique(transaction)
unique

array(['T0001', 'T0002', 'T0003', 'T0004', 'T0005', 'T0006', 'T0007',
       'T0008', 'T0009', 'T0010', 'T0011', 'T0012', 'T0013', 'T0014',
       'T0015', 'T0016', 'T0017', 'T0018', 'T0019', 'T0020', 'T0021',
       'T0022', 'T0023', 'T0024', 'T0025', 'T0026', 'T0027', 'T0028',
       'T0029', 'T0030', 'T0031', 'T0032', 'T0033', 'T0034', 'T0035',
       'T0036', 'T0037', 'T0038', 'T0039', 'T0040', 'T0041', 'T0042',
       'T0043', 'T0044', 'T0045', 'T0046', 'T0047', 'T0048', 'T0049',
       'T0050'], dtype=object)

In [74]:
order=[]
for i in unique:
    order.append(np.mean(amount[transaction==i]))
avg_order_value=np.mean(order)

In [75]:
avg_order_value

np.float64(11969.7)

In [76]:
category=df['ProductCategory'].values
category

array(['Electronics', 'Clothing', 'Grocery', 'Electronics', 'Furniture',
       'Clothing', 'Beauty', 'Grocery', 'Electronics', 'Clothing',
       'Sports', 'Beauty', 'Furniture', 'Grocery', 'Clothing',
       'Electronics', 'Home Decor', 'Grocery', 'Sports', 'Clothing',
       'Beauty', 'Electronics', 'Home Decor', 'Grocery', 'Clothing',
       'Furniture', 'Beauty', 'Sports', 'Grocery', 'Electronics',
       'Home Decor', 'Clothing', 'Grocery', 'Furniture', 'Electronics',
       'Beauty', 'Grocery', 'Clothing', 'Home Decor', 'Sports',
       'Furniture', 'Clothing', 'Electronics', 'Beauty', 'Grocery',
       'Home Decor', 'Clothing', 'Sports', 'Furniture', 'Electronics'],
      dtype=object)

In [77]:
electronics=amount[category=='Electronics']
electronics

array([45000,  3000, 52000, 38000, 41000, 46000, 50000, 37000, 49000])

In [78]:
np.mean(electronics)

np.float64(40111.11111111111)

In [79]:
np.std(electronics)

np.float64(14019.386929411114)

Section F – Advanced / open‑ended questions
Based on your analysis, which three customer segments (by age group and/or gender) would you target for a marketing campaign and why?

Which product categories appear suitable for discount/promotion (for example, high quantity but low revenue, or high variance in TotalAmount)?

Propose two concrete business recommendations for the retail store using your findings.

If you want, I can next generate a ready‑to‑run Jupyter notebook skeleton that loads this dataset and structures code cells according to these questions.